import type { Localized } from "@/lib/i18n";
import type { Level } from "@/lib/status";

const A: Level = "available";

const en = {
  meta: {
    title: "Build with Ghostly",
    description:
      "Ghost is a small rendezvous primitive on Pkarr / Mainline DHT. Ghostly composes it with transports, capabilities and local state. Read the WISP contracts, see real code, build your own client or adapter.",
  },
  hero: {
    eyebrow: "For developers",
    title: "Two peers. A DHT. A direct line.",
    lead: "Each app publishes a small signed record to the Mainline DHT, finds the other's, keeps what both speak and opens a direct connection. Every step is an open contract, a WISP.",
    ctaCore: "WISP 01 · Ghost Core",
    ctaCatalog: "Browse {n} WISPs",
    ctaCode: "GitHub",
    steps: {
      label: "How a chat starts, step by step",
      of: "Step {n} of {total}",
      stepsLabel: "Steps",
      prev: "Previous",
      next: "Next",
      replay: "Replay step",
      playAll: "Play all",
      pause: "Pause",
      restart: "From the start",
      keys: "← → to step",
      wisps: "Specified in",
      sent: "On the wire",
      stage: {
        boo: "Boo",
        casper: "Casper",
        dht: "Mainline DHT · Pkarr relays",
        dhtShort: "Mainline DHT",
        oob: "link or QR, out of band",
        pinned: "pinned",
        common: "3 in common",
        off: "off",
        live: "live",
        onDht: "on DHT · retrying live",
        onDhtShort: "on DHT",
        back: "live again",
        presence: "presence",
        dmEnvelope: "_dm envelope",
        rtcOffer: "_rtc offer",
        dmText: "_dm · text up to 256 B",
        dmShort: "_dm · 256 B",
        direct: "direct",
        relayed: "relayed",
        relayedShort: "relayed",
        pay: "pay · 2,100 sat",
      },
      list: [
        {
          id: "publish",
          short: "Publish",
          title: "Each app signs a record",
          body: "Boo's app puts two small signed records on the Mainline DHT: its presence and its capability record. Browsers reach the DHT through Pkarr relays.",
          wisps: ["01", "03"],
          wire: [
            { k: "packet", v: "signed DNS packet, at most 1,000 bytes" },
            { k: "_caps", v: "transports · capabilities · descriptors · name" },
            { k: "descriptors", v: "Iroh endpoint id, HyperDHT key, never an address" },
            { k: "sealed", v: "with the invite secret, until the contact is pinned" },
          ],
        },
        {
          id: "invite",
          short: "Invite",
          title: "One code carries the keys",
          body: "Boo shares a ghostly1 code by link or QR. It carries Casper's seed, Boo's keys and the invite secret, so Casper knows Boo's key before anything answers.",
          wisps: ["801"],
          wire: [
            { k: "code", v: "ghostly1p…, bech32m, 220 characters" },
            { k: "128 bytes", v: "joining seed · Boo's rendezvous key · invite secret · Boo's participation key" },
            { k: "link", v: "ghostly.tools/#ghostly1p…, the fragment never reaches a server" },
          ],
        },
        {
          id: "contact",
          short: "First contact",
          title: "Two first contacts at once",
          body: "Casper knocks on both layers: a signed envelope in his DHT mailbox and a WebRTC offer. Boo pins Casper's key from whichever arrives first. Another key on the other path is rejected.",
          wisps: ["400", "403", "101"],
          wire: [
            { k: "_dm", v: "envelope signed by Casper's participation key, sealed with the invite key" },
            { k: "_rtc", v: "WebRTC offer: ICE credentials, DTLS fingerprint, candidates" },
            { k: "pin", v: "the same key on both paths, or a security rejection" },
          ],
        },
        {
          id: "offers",
          short: "Offers",
          title: "Keep what both speak",
          body: "Each app lists what it can do: first in its capability record, then in the signed pair-offer of the session. Only what both list is turned on.",
          wisps: ["03", "401"],
          wire: [
            { k: "Boo", v: "chat/1 · files/2 · payments/1 · hold/1" },
            { k: "Casper", v: "chat/1 · files/2 · payments/1" },
            { k: "on", v: "chat/1 · files/2 · payments/1; hold/1 needs both" },
            { k: "pair-offer", v: "versions · transports · capabilities · key · nonce" },
          ],
        },
        {
          id: "transport",
          short: "Transport",
          title: "Rank the transports",
          body: "The dialing side adds up each shared transport's place on both lists, and the lowest sum goes first. A relayed path always waits behind a direct one.",
          wisps: ["100"],
          wire: [
            { k: "Boo", v: "iroh/1 · hyperdht/1 · webrtc/1 (desktop, prefers Iroh)" },
            { k: "Casper", v: "webrtc/1 · iroh/1 (browser: Iroh through a relay)" },
            { k: "webrtc/1", v: "3 + 1 = 4, direct: goes first" },
            { k: "iroh/1", v: "1 + 2 = 3, relayed: next, if WebRTC fails" },
            { k: "dials", v: "the lower rendezvous key; ties go Iroh, HyperDHT, WebRTC" },
          ],
        },
        {
          id: "proof",
          short: "Proof",
          title: "Bind the session to this line",
          body: "Each side signs a transcript of both offers and of the connection itself, then confirms its digest. A proof replayed over another connection does not verify.",
          wisps: ["401", "101", "102", "103"],
          wire: [
            { k: "pair-proof", v: "Ed25519 signature over the transcript" },
            { k: "binding", v: "WebRTC: DTLS fingerprints · Iroh: TLS exporter · HyperDHT: handshake hash" },
            { k: "pair-ready", v: "SHA-256 of the transcript; its first 24 hex digits are the comparison code" },
          ],
        },
        {
          id: "frames",
          short: "Live",
          title: "Messages, files, payments",
          body: "On the live line a message is stored before its receipt goes back. Files go in 16 KiB pieces, resume where they stopped and end on a SHA-256 check. A payment is its own frame.",
          wisps: ["400", "501", "200"],
          wire: [
            { k: "paired-message", v: "id · ts · text up to 16 KiB, answered by paired-received" },
            { k: "files/3", v: "pf-offer → pf-accept → pf-data → pf-sum → pf-done" },
            { k: "payments", v: "pay-req · pay · pay-res; paying needs the live line" },
          ],
        },
        {
          id: "floor",
          short: "Floor",
          title: "The DHT is the floor",
          body: "When the line drops, short texts go through the DHT mailbox and the rest waits. The line is retried in the background, and the queue goes in order once it is back.",
          wisps: ["400", "403", "100"],
          wire: [
            { k: "drop", v: "the channel closes, or 3 pings in a row go unanswered" },
            { k: "_dm", v: "one text of up to 256 bytes at a time, under the same message id" },
            { k: "waits", v: "files, payment requests and long texts, or held where both allow" },
            { k: "retry", v: "at once when the contact is seen; after a failed try, 20 s doubling to 3 min" },
          ],
        },
      ],
    },
  },
  compose: {
    eyebrow: "01 · Composition",
    title: "Pick the pieces. See what you get.",
    lead: "Each row is an area of the architecture, each block a piece with its own contract. Pick a composition: it lights the pieces it needs.",
    presets: "Compositions",
    selectHint: "Tap a block for what it does and the WISP that specifies it.",
    close: "Close",
    enables: "What it enables",
    specs: "Specified in",
    noSpec: "No WISP yet",
    docs: "Reference",
    included: "{n} of {t} pieces",
    boardLabel: "Architecture board",
  },
  negotiate: {
    eyebrow: "02 · Negotiation",
    title: "Two peers. One honest answer.",
    lead: "Each side offers what it has, in its own order. What both have is ranked by both orders together. Nothing in common means no.",
    scenarios: "Scenario",
    scenarioNames: {
      match: "Desktop ↔ desktop",
      browser: "Desktop ↔ browser",
      none: "No common transport",
      partial: "Payments on one side",
    },
    captions: {
      match: "A tie at 3: the fixed order breaks it, iroh first.",
      browser: "The browser speaks only WebRTC. Arkade is off on Casper's side.",
      none: "Fallback is off on the desktop, so it offers Iroh alone.",
      partial: "Chat and files go ahead; Cashu stays off.",
    },
    phases: {
      offers: "Offers go out",
      ranked: "Transports ranked",
      agreed: "Capabilities agreed",
      nothing: "Nothing in common",
      none: "No connection",
    },
    platforms: { desktop: "Desktop app", browser: "Browser" },
    tags: { fallbackOff: "fallback off", arkadeOff: "Arkade off", paymentsOff: "payments off" },
    transports: "Transports, in order",
    capabilities: "Capabilities",
    result: "Result",
    comparing: "Comparing offers…",
    agreed: "Agreed",
    order: "Try in this order",
    sum: "position on Boo's list + position on Casper's list; lower wins",
    off: "Stays off",
    fail: "No connection",
    failBody: "Nothing in common. Nothing bridges WebRTC to Iroh; a bridge would be its own integration, with its own trust.",
    first: "The first stream of a new chat is WebRTC. Iroh and HyperDHT can follow without it: their descriptors travel in the capability record on the DHT. A pairing with no path at all goes on over the DHT.",
    rule: "Same rule as rankTransports() in packages/core/src/pairedTransports.ts",
    simplified: "offers simplified",
    status: "Every chat: web, desktop and extension",
    boo: "Boo",
    casper: "Casper",
  },
  path: {
    eyebrow: "03 · Your path",
    title: "From reading to building.",
    steps: [
      {
        title: "Understand the core",
        body: "Signed Pkarr records: at most 1000 bytes, a 300-second TTL.",
        links: [
          { label: "WISP 01 · Ghost Core", href: "/developers/wisps/01-ghost-core" },
          { label: "The Ghost Protocol", href: "/developers/wisps/protocol" },
        ],
      },
      {
        title: "Read a contract",
        body: "Pick one family: chat, files or payments.",
        links: [
          { label: "WISP 400 · Chat", href: "/developers/wisps/400-chat" },
          { label: "WISP 500 · Files", href: "/developers/wisps/500-files" },
          { label: "WISP 200 · Payments", href: "/developers/wisps/200-payments" },
        ],
      },
      {
        title: "Build a client or adapter",
        body: "The protocol library, the SDK, the native transports and a Rust CLI.",
        links: [
          { label: "packages/core", href: "https://github.com/MiguelMedeiros/ghostly/tree/dev/packages/core/src" },
          { label: "packages/sdk", href: "https://github.com/MiguelMedeiros/ghostly/tree/dev/packages/sdk" },
          { label: "native-transports", href: "https://github.com/MiguelMedeiros/ghostly/tree/dev/native-transports" },
          { label: "cli", href: "https://github.com/MiguelMedeiros/ghostly/tree/dev/cli" },
          { label: "CLI guide", href: "/cli" },
        ],
      },
    ],
  },
  availability: {
    eyebrow: "04 · Where it runs",
    title: "Client by client.",
    lead: "The same feature can be available in one client and not another. This is the honest map.",
    feature: "Feature",
    clients: ["Web app", "Desktop", "Extension", "CLI"],
    none: "No",
    rows: [
      { name: "Text chat", cells: [A, A, A, A] },
      { name: "Pinned keys, durable outbox", cells: [A, A, A, null] },
      { name: "Files of any size, resumed", cells: [A, A, A, null] },
      { name: "Voice messages", cells: [A, A, A, null] },
      { name: "Voice, video, screen", cells: [A, A, A, null] },
      { name: "Iroh (browsers through relays)", cells: [A, A, A, null] },
      { name: "HyperDHT (browsers only through a relay you set; not yet on Intel Macs)", cells: [A, A, A, null] },
      { name: "Host / open a local app", cells: [null, A, A, null] },
      { name: "Cashu & Lightning wallet", cells: [A, A, A, null] },
      { name: "Your own Lightning source (NWC, LND, CLN, WebLN, Breez, Fedimint)", cells: [A, A, A, null] },
      { name: "Lightning addresses, paying from another wallet", cells: [A, A, A, null] },
      { name: "Ark (Arkade, Bark), Spark, Fedimint & USDT wallets", cells: [A, A, A, null] },
      { name: "On-chain bitcoin (BDK, Bitcoin Core)", cells: [A, A, A, null] },
      { name: "Local profiles", cells: [A, A, A, null] },
      { name: "Backups (file, S3)", cells: [A, A, A, null] },
      { name: "Messages held for an away contact (your S3)", cells: [A, A, A, null] },
      { name: "Identity proofs (Nostr, Pubky, domain, OpenPGP, SSH, Bitcoin, DID)", cells: [A, A, A, null] },
      { name: "Nostr social layer (profile, follows, notes)", cells: [A, A, A, null] },
      { name: "Private groups (up to 8) and communities (up to 256)", cells: [A, A, A, null] },
      { name: "Payments in groups", cells: [A, A, A, null] },
    ] as { name: string; cells: (Level | null)[] }[],
    notes: [
      "One chat (WISPs 400 and 801): a chat with no direct path starts on the DHT and goes live by itself; one ghostly1… invite code with a ghostly.tools link, which the CLI does not read.",
      "Calls: in every chat while it is live, not in groups. Groups: text, a picture and payments; no files or calls. CLI: DHT text in the 0.4 format, keys passed by hand. Desktop on Linux: its webview has no WebRTC, so no calls there, and it goes live only with another desktop app, over Iroh or HyperDHT.",
      "WebLN is web-only, Bitcoin Core desktop-only. Bark, BDK, Breez and Fedimint run on test networks only; Spark needs your own Breez API key for Mainnet. OpenID waits for OAuth clients; Bluesky for its OAuth client document on ghostly.tools.",
      "Also contacted: Pkarr relays, Google STUN, mints, Iroh relays, HyperDHT bootstrap nodes, Ark and Spark operators, Fedimint guardians, Esplora servers, Nostr relays, Ethereum RPCs, and any service you add. No TURN by default.",
    ],
  },
  next: {
    catalog: { title: "The WISP catalog", body: "Every WISP, searchable, with its status and implementations.", cta: "Open the catalog" },
    roadmap: { title: "The roadmap", body: "What comes next, in dependency order. No dates.", cta: "See the roadmap" },
    docs: { title: "Protocol docs", body: "The long-form walkthrough of the protocol.", cta: "Read the docs" },
  },
};

export type DevCopy = typeof en;

const ptBr: DevCopy = {
  meta: {
    title: "Construa com o Ghostly",
    description:
      "Ghost é uma primitiva pequena de encontro sobre Pkarr / DHT Mainline. O Ghostly a compõe com transportes, capacidades e estado local. Leia os contratos WISP, veja código real, construa seu próprio cliente ou adapter.",
  },
  hero: {
    eyebrow: "Para desenvolvedores",
    title: "Dois peers. Uma DHT. Uma linha direta.",
    lead: "Cada app publica um pequeno registro assinado na DHT Mainline, acha o do outro, fica com o que os dois falam e abre uma conexão direta. Cada passo é um contrato aberto, um WISP.",
    ctaCore: "WISP 01 · Ghost Core",
    ctaCatalog: "Ver os {n} WISPs",
    ctaCode: "GitHub",
    steps: {
      label: "Como um chat começa, passo a passo",
      of: "Passo {n} de {total}",
      stepsLabel: "Passos",
      prev: "Anterior",
      next: "Próximo",
      replay: "Rever o passo",
      playAll: "Tocar tudo",
      pause: "Pausar",
      restart: "Do começo",
      keys: "← → para andar",
      wisps: "Especificado em",
      sent: "No fio",
      stage: {
        boo: "Boo",
        casper: "Casper",
        dht: "DHT Mainline · relays Pkarr",
        dhtShort: "DHT Mainline",
        oob: "link ou QR, por fora",
        pinned: "fixada",
        common: "3 em comum",
        off: "fora",
        live: "ao vivo",
        onDht: "na DHT · tentando ao vivo",
        onDhtShort: "na DHT",
        back: "ao vivo de novo",
        presence: "presença",
        dmEnvelope: "_dm envelope",
        rtcOffer: "_rtc oferta",
        dmText: "_dm · texto até 256 B",
        dmShort: "_dm · 256 B",
        direct: "direto",
        relayed: "via relay",
        relayedShort: "relay",
        pay: "pay · 2.100 sat",
      },
      list: [
        {
          id: "publish",
          short: "Publicar",
          title: "Cada app assina um registro",
          body: "O app do Boo põe dois registros pequenos e assinados na DHT Mainline: a presença e o registro de capacidades. Navegadores chegam à DHT pelos relays Pkarr.",
          wisps: ["01", "03"],
          wire: [
            { k: "pacote", v: "pacote DNS assinado, no máximo 1.000 bytes" },
            { k: "_caps", v: "transportes · capacidades · descritores · nome" },
            { k: "descritores", v: "id do endpoint Iroh, chave HyperDHT, nunca um endereço" },
            { k: "selado", v: "com o segredo do convite, até o contato ser fixado" },
          ],
        },
        {
          id: "invite",
          short: "Convite",
          title: "Um código leva as chaves",
          body: "O Boo manda um código ghostly1 por link ou QR. Ele leva a semente do Casper, as chaves do Boo e o segredo do convite, então o Casper já sabe a chave do Boo antes de qualquer resposta.",
          wisps: ["801"],
          wire: [
            { k: "código", v: "ghostly1p…, bech32m, 220 caracteres" },
            { k: "128 bytes", v: "semente de entrada · chave de encontro do Boo · segredo do convite · chave de participação do Boo" },
            { k: "link", v: "ghostly.tools/#ghostly1p…, o fragmento nunca chega a um servidor" },
          ],
        },
        {
          id: "contact",
          short: "Primeiro contato",
          title: "Dois primeiros contatos ao mesmo tempo",
          body: "O Casper bate nas duas camadas: um envelope assinado na caixa dele na DHT e uma oferta WebRTC. O Boo fixa a chave do Casper pelo que chegar primeiro. Outra chave no outro caminho é recusada.",
          wisps: ["400", "403", "101"],
          wire: [
            { k: "_dm", v: "envelope assinado pela chave de participação do Casper, selado com a chave do convite" },
            { k: "_rtc", v: "oferta WebRTC: credenciais ICE, impressão DTLS, candidatos" },
            { k: "fixar", v: "a mesma chave nos dois caminhos, ou uma recusa de segurança" },
          ],
        },
        {
          id: "offers",
          short: "Ofertas",
          title: "Fica o que os dois falam",
          body: "Cada app lista o que sabe fazer: primeiro no registro de capacidades, depois no pair-offer assinado da sessão. Só liga o que os dois listam.",
          wisps: ["03", "401"],
          wire: [
            { k: "Boo", v: "chat/1 · files/2 · payments/1 · hold/1" },
            { k: "Casper", v: "chat/1 · files/2 · payments/1" },
            { k: "ligado", v: "chat/1 · files/2 · payments/1; hold/1 precisa dos dois" },
            { k: "pair-offer", v: "versões · transportes · capacidades · chave · nonce" },
          ],
        },
        {
          id: "transport",
          short: "Transporte",
          title: "Ordenar os transportes",
          body: "Quem disca soma a posição de cada transporte em comum nas duas listas, e a menor soma vai primeiro. Um caminho por relay sempre espera atrás de um direto.",
          wisps: ["100"],
          wire: [
            { k: "Boo", v: "iroh/1 · hyperdht/1 · webrtc/1 (desktop, prefere Iroh)" },
            { k: "Casper", v: "webrtc/1 · iroh/1 (navegador: Iroh por um relay)" },
            { k: "webrtc/1", v: "3 + 1 = 4, direto: vai primeiro" },
            { k: "iroh/1", v: "1 + 2 = 3, por relay: o próximo, se o WebRTC falhar" },
            { k: "disca", v: "a menor chave de encontro; empate vai Iroh, HyperDHT, WebRTC" },
          ],
        },
        {
          id: "proof",
          short: "Prova",
          title: "Amarrar a sessão a esta linha",
          body: "Cada lado assina uma transcrição das duas ofertas e da própria conexão, depois confirma o resumo dela. Uma prova repetida em outra conexão não verifica.",
          wisps: ["401", "101", "102", "103"],
          wire: [
            { k: "pair-proof", v: "assinatura Ed25519 sobre a transcrição" },
            { k: "vínculo", v: "WebRTC: impressões DTLS · Iroh: exportador TLS · HyperDHT: hash do handshake" },
            { k: "pair-ready", v: "SHA-256 da transcrição; os 24 primeiros dígitos hex são o código de comparação" },
          ],
        },
        {
          id: "frames",
          short: "Ao vivo",
          title: "Mensagens, arquivos, pagamentos",
          body: "Na linha ao vivo a mensagem é guardada antes de o recibo voltar. Arquivos vão em pedaços de 16 KiB, retomam de onde pararam e terminam com um SHA-256. Um pagamento é um frame próprio.",
          wisps: ["400", "501", "200"],
          wire: [
            { k: "paired-message", v: "id · ts · texto de até 16 KiB, respondido por paired-received" },
            { k: "files/3", v: "pf-offer → pf-accept → pf-data → pf-sum → pf-done" },
            { k: "pagamentos", v: "pay-req · pay · pay-res; pagar precisa da linha ao vivo" },
          ],
        },
        {
          id: "floor",
          short: "Piso",
          title: "A DHT é o piso",
          body: "Quando a linha cai, textos curtos vão pela caixa na DHT e o resto espera. A linha é tentada de novo em segundo plano, e a fila sai em ordem quando ela volta.",
          wisps: ["400", "403", "100"],
          wire: [
            { k: "queda", v: "o canal fecha, ou 3 pings seguidos ficam sem resposta" },
            { k: "_dm", v: "um texto de até 256 bytes por vez, com o mesmo id de mensagem" },
            { k: "espera", v: "arquivos, pedidos de pagamento e textos longos, ou guardados onde os dois permitem" },
            { k: "retentar", v: "na hora quando o contato aparece; depois de uma falha, 20 s dobrando até 3 min" },
          ],
        },
      ],
    },
  },
  compose: {
    eyebrow: "01 · Composição",
    title: "Escolha as peças. Veja o que sai.",
    lead: "Cada linha é uma área da arquitetura; cada bloco, uma peça com o próprio contrato. Escolha uma composição: ela acende as peças de que precisa.",
    presets: "Composições",
    selectHint: "Toque num bloco para ver o que ele faz e a WISP que o especifica.",
    close: "Fechar",
    enables: "O que permite",
    specs: "Especificado em",
    noSpec: "Ainda sem WISP",
    docs: "Referência",
    included: "{n} de {t} peças",
    boardLabel: "Tabuleiro da arquitetura",
  },
  negotiate: {
    eyebrow: "02 · Negociação",
    title: "Dois peers. Uma resposta honesta.",
    lead: "Cada lado oferece o que tem, na própria ordem. O que os dois têm é ordenado pelas duas ordens juntas. Nada em comum quer dizer não.",
    scenarios: "Cenário",
    scenarioNames: {
      match: "Desktop ↔ desktop",
      browser: "Desktop ↔ navegador",
      none: "Sem transporte em comum",
      partial: "Pagamento só de um lado",
    },
    captions: {
      match: "Empate em 3: a ordem fixa desempata, iroh primeiro.",
      browser: "O navegador só fala WebRTC. Arkade está desligado do lado do Casper.",
      none: "O desktop está sem fallback, então oferece só Iroh.",
      partial: "Chat e arquivos seguem; Cashu fica de fora.",
    },
    phases: {
      offers: "Ofertas enviadas",
      ranked: "Transportes ordenados",
      agreed: "Capacidades combinadas",
      nothing: "Nada em comum",
      none: "Sem conexão",
    },
    platforms: { desktop: "App desktop", browser: "Navegador" },
    tags: { fallbackOff: "sem fallback", arkadeOff: "Arkade desligado", paymentsOff: "pagamentos desligados" },
    transports: "Transportes, em ordem",
    capabilities: "Capacidades",
    result: "Resultado",
    comparing: "Comparando ofertas…",
    agreed: "Combinado",
    order: "Tentar nesta ordem",
    sum: "posição na lista do Boo + posição na lista do Casper; menor vence",
    off: "Fica de fora",
    fail: "Sem conexão",
    failBody: "Nada em comum. Nada faz ponte entre WebRTC e Iroh; uma ponte seria uma integração própria, com a própria confiança.",
    first: "O primeiro stream de um chat novo é WebRTC. Iroh e HyperDHT podem vir sem ele: os descritores deles vão no registro de capacidades na DHT. Um pareamento sem caminho nenhum segue pela DHT.",
    rule: "A mesma regra de rankTransports() em packages/core/src/pairedTransports.ts",
    simplified: "ofertas simplificadas",
    status: "Todo chat: web, desktop e extensão",
    boo: "Boo",
    casper: "Casper",
  },
  path: {
    eyebrow: "03 · Seu caminho",
    title: "Da leitura à construção.",
    steps: [
      {
        title: "Entenda o núcleo",
        body: "Registros Pkarr assinados: no máximo 1000 bytes, TTL de 300 segundos.",
        links: [
          { label: "WISP 01 · Ghost Core", href: "/pt-br/developers/wisps/01-ghost-core" },
          { label: "O protocolo Ghost", href: "/pt-br/developers/wisps/protocol" },
        ],
      },
      {
        title: "Leia um contrato",
        body: "Escolha uma família: chat, arquivos ou pagamentos.",
        links: [
          { label: "WISP 400 · Chat", href: "/pt-br/developers/wisps/400-chat" },
          { label: "WISP 500 · Arquivos", href: "/pt-br/developers/wisps/500-files" },
          { label: "WISP 200 · Pagamentos", href: "/pt-br/developers/wisps/200-payments" },
        ],
      },
      {
        title: "Construa um cliente ou adapter",
        body: "A biblioteca do protocolo, o SDK, os transportes nativos e uma CLI em Rust.",
        links: [
          { label: "packages/core", href: "https://github.com/MiguelMedeiros/ghostly/tree/dev/packages/core/src" },
          { label: "packages/sdk", href: "https://github.com/MiguelMedeiros/ghostly/tree/dev/packages/sdk" },
          { label: "native-transports", href: "https://github.com/MiguelMedeiros/ghostly/tree/dev/native-transports" },
          { label: "cli", href: "https://github.com/MiguelMedeiros/ghostly/tree/dev/cli" },
          { label: "Guia da CLI (em inglês)", href: "/cli" },
        ],
      },
    ],
  },
  availability: {
    eyebrow: "04 · Onde roda",
    title: "Cliente por cliente.",
    lead: "O mesmo recurso pode existir num cliente e não em outro. Este é o mapa honesto.",
    feature: "Recurso",
    clients: ["App web", "Desktop", "Extensão", "CLI"],
    none: "Não",
    rows: [
      { name: "Chat de texto", cells: [A, A, A, A] },
      { name: "Chaves fixadas, caixa de saída durável", cells: [A, A, A, null] },
      { name: "Arquivos de qualquer tamanho, retomados", cells: [A, A, A, null] },
      { name: "Mensagens de voz", cells: [A, A, A, null] },
      { name: "Voz, vídeo, tela", cells: [A, A, A, null] },
      { name: "Iroh (navegadores por relays)", cells: [A, A, A, null] },
      { name: "HyperDHT (navegadores só por um relay que você define; ainda não em Macs Intel)", cells: [A, A, A, null] },
      { name: "Hospedar / abrir app local", cells: [null, A, A, null] },
      { name: "Carteira Cashu e Lightning", cells: [A, A, A, null] },
      { name: "Sua própria fonte Lightning (NWC, LND, CLN, WebLN, Breez, Fedimint)", cells: [A, A, A, null] },
      { name: "Lightning addresses, pagar com outra carteira", cells: [A, A, A, null] },
      { name: "Carteiras Ark (Arkade, Bark), Spark, Fedimint e USDT", cells: [A, A, A, null] },
      { name: "Bitcoin on-chain (BDK, Bitcoin Core)", cells: [A, A, A, null] },
      { name: "Perfis locais", cells: [A, A, A, null] },
      { name: "Backups (arquivo, S3)", cells: [A, A, A, null] },
      { name: "Mensagens guardadas para um contato ausente (seu S3)", cells: [A, A, A, null] },
      { name: "Provas de identidade (Nostr, Pubky, domínio, OpenPGP, SSH, Bitcoin, DID)", cells: [A, A, A, null] },
      { name: "Camada social do Nostr (perfil, quem segue, notas)", cells: [A, A, A, null] },
      { name: "Grupos privados (até 8) e comunidades (até 256)", cells: [A, A, A, null] },
      { name: "Pagamentos em grupos", cells: [A, A, A, null] },
    ],
    notes: [
      "Um só chat (WISPs 400 e 801): um chat sem caminho direto começa na DHT e passa sozinho ao link direto; um único código de convite ghostly1… com link em ghostly.tools, que a CLI não lê.",
      "Chamadas: em todo chat enquanto ele está ao vivo, não em grupos. Grupos: texto, uma foto e pagamentos; sem arquivos nem chamadas. CLI: texto pela DHT no formato do 0.4, chaves à mão. Desktop no Linux: o webview não tem WebRTC, então sem chamadas lá, e ele só fica ao vivo com outro app desktop, por Iroh ou HyperDHT.",
      "WebLN só na web, Bitcoin Core só no desktop. Bark, BDK, Breez e Fedimint só em redes de teste; o Spark exige a sua própria chave de API da Breez na Mainnet. OpenID espera os clientes OAuth; o Bluesky, o documento de cliente OAuth dele em ghostly.tools.",
      "Também contatados: relays Pkarr, STUN do Google, mints, relays Iroh, nós de bootstrap da HyperDHT, operadores Ark e Spark, guardiões Fedimint, servidores Esplora, relays Nostr, RPCs Ethereum e o serviço que você adicionar. Sem TURN por padrão.",
    ],
  },
  next: {
    catalog: { title: "O catálogo de WISPs", body: "Todos os WISPs, com busca, status e implementações.", cta: "Abrir o catálogo" },
    roadmap: { title: "O roadmap", body: "O que vem depois, na ordem das dependências, sem datas.", cta: "Ver o roadmap" },
    docs: { title: "Docs do protocolo", body: "O passo a passo longo do protocolo (em inglês).", cta: "Ler os docs" },
  },
};

export const developers: Localized<DevCopy> = { en, "pt-br": ptBr };
