import type { Localized } from "@/lib/i18n";
import type { Level } from "@/lib/status";

const en = {
  meta: {
    title: "Build with Ghostly",
    description:
      "Ghost is a small rendezvous primitive on Pkarr / Mainline DHT. Ghostly composes it with transports, capabilities and local state. Read the WISP contracts, see real code, build your own client or adapter.",
  },
  hero: {
    eyebrow: "For developers",
    title1: "Ghost is small on purpose.",
    title2: "Compose the rest.",
    lead: "Ghost is the rendezvous primitive: small signed records on Pkarr and the Mainline DHT, just enough for two peers to find each other and agree. Ghostly is one reference app that composes it with transports, abilities and local state. Yours can be much smaller.",
    ctaCore: "Read the core contract",
    ctaCatalog: "Browse {n} WISPs",
    ctaCode: "Source on GitHub",
  },
  words: {
    eyebrow: "01 — Six words",
    title: "The vocabulary, before the diagram.",
    lead: "Most confusion comes from mixing these up. A WISP is not a plugin; a protocol profile is not your local profile.",
    items: [
      {
        id: "wisp",
        term: "WISP",
        says: "A specification.",
        body: "An interoperable contract anyone can implement. It describes behavior, not an installed feature — and a new logo doesn't need one.",
        example: "WISP 500 · File Transfer",
      },
      {
        id: "capability",
        term: "Capability",
        says: "What a client announces.",
        body: "A versioned ability a running client actually offers in a session. Both sides use only what they both announce.",
        example: "files/2 · payments-cashu/1",
      },
      {
        id: "adapter",
        term: "Adapter",
        says: "One technology, plugged in.",
        body: "An implementation of a contract with a specific technology. Two adapters of the same contract aren't automatically compatible with each other.",
        example: "WebRTC (101) · Cashu (201)",
      },
      {
        id: "profile",
        term: "Protocol profile",
        says: "The concrete rules.",
        body: "An exact combination and wire binding of pieces. Not to be confused with a local profile, which is where a person's data lives on a device.",
        example: "Paired Chat (401) ≠ Local Profiles (04)",
      },
      {
        id: "plugin",
        term: "Plugin",
        says: "A possible package.",
        body: "A future way to distribute adapters, interfaces or apps. Packaging, not a specification — and not available yet.",
        example: "planned",
        level: "planned" as Level,
      },
      {
        id: "provider",
        term: "Provider / signer",
        says: "Who performs or authorizes.",
        body: "A service or component that executes or approves a specific function. Sharing a key curve with a signer doesn't mean integrating with it.",
        example: "a Cashu mint · an Ark operator · an Ethereum RPC",
      },
    ],
  },
  compose: {
    eyebrow: "02 — Composition",
    title: "Pick the pieces. See what you get.",
    lead: "Each block is a piece with its own contract. Choose a composition, then select any block to see what it enables and where it's specified.",
    presets: "Compositions",
    selectHint: "Select a block",
    enables: "What it enables",
    specs: "Specified in",
    noSpec: "No WISP yet",
    docs: "Reference",
    included: "{n} of {t} pieces",
    boardLabel: "Architecture board",
  },
  negotiate: {
    eyebrow: "03 — Negotiation",
    title: "Two peers. One honest answer.",
    lead: "A conceptual demo of the paired-session rule: each side offers what it has, in its own order; the intersection is ranked by both orders together. If there's nothing in common, the answer is no.",
    note: "Transport ranking uses the same rule as packages/core/src/pairedTransports.ts. Capabilities are simplified. Paired sessions are in development.",
    scenarios: "Try a scenario",
    scenarioNames: {
      match: "Desktop ↔ desktop",
      browser: "Desktop ↔ browser",
      none: "No common transport",
      partial: "Payments only on one side",
    },
    platform: "Runs on",
    platforms: { desktop: "Desktop app", browser: "Browser", extension: "Extension" },
    transports: "What it offers, in order",
    preferred: "Preferred transport",
    capabilities: "Capabilities",
    fallback: "Allow fallback",
    up: "Move up",
    result: "Result",
    agreed: "Agreed",
    order: "Try in this order",
    off: "Stays off",
    fail: "No common transport. No connection — and nothing silently bridges WebRTC to Iroh. A bridge would be its own integration, with its own trust.",
    noFallback: "Fallback is off on one side, so only the first choice is tried.",
    offer: "What Boo sends (shape of a real pair-offer)",
    boo: "Boo",
    casper: "Casper",
    unavailable: "not available on this platform",
  },
  path: {
    eyebrow: "04 — Your path",
    title: "From reading to building.",
    lead: "Real files, real commands. Nothing here is an SDK we haven't written.",
    steps: [
      {
        title: "Understand the core",
        body: "How two peers meet: signed Pkarr records, 1000-byte packets, 300-second TTL.",
        links: [
          { label: "WISP 01 · Ghost Core", href: "/developers/wisps/01-ghost-core" },
          { label: "The Ghost Protocol", href: "/developers/wisps/protocol" },
        ],
      },
      {
        title: "Read a contract",
        body: "Start with one family: chat, files or payments. Each contract lists its adapters and profiles.",
        links: [
          { label: "WISP 400 · Chat", href: "/developers/wisps/400-chat" },
          { label: "WISP 100 · Transports", href: "/developers/wisps/100-transports" },
        ],
      },
      {
        title: "See a real implementation",
        body: "The TypeScript core, the native transports and the Rust CLI are all in the repository.",
        code: "packages/core/src/invite.ts",
        links: [
          { label: "packages/core", href: "https://github.com/MiguelMedeiros/ghostly/tree/dev/packages/core/src" },
          { label: "native-transports", href: "https://github.com/MiguelMedeiros/ghostly/tree/dev/native-transports" },
          { label: "cli", href: "https://github.com/MiguelMedeiros/ghostly/tree/dev/cli" },
        ],
      },
      {
        title: "Build a client or adapter",
        body: "The CLI is a complete small client: identity, invitation, send and a JSON stream. Script it, or implement the same contracts in your language.",
        links: [{ label: "CLI guide", href: "/cli" }],
      },
      {
        title: "Contribute",
        body: "Propose a change to a draft, report what didn't match, or add an adapter. Drafts become Final only with two independent implementations.",
        links: [
          { label: "WISP 00 · Process", href: "/developers/wisps/00-process" },
          { label: "Contributing", href: "/developers/wisps/contributing" },
        ],
      },
    ],
    codeCaption: "From packages/core/src/invite.ts — both ends of a link are created at once.",
  },
  availability: {
    eyebrow: "05 — Where it runs",
    title: "Client by client.",
    lead: "The same feature can be available in one client and not another. This is the honest map.",
    feature: "Feature",
    clients: ["Web app", "Desktop", "Extension", "CLI"],
    none: "—",
    rows: [
      { name: "Text chat", cells: ["released", "released", "released", "released"] },
      { name: "Paired chats, pinned keys", cells: ["development", "development", "development", null] },
      { name: "Files (100 MiB)", cells: ["released", "released", "released", null] },
      { name: "Voice, video, screen", cells: ["released", "released", "released", null] },
      { name: "Iroh & HyperDHT", cells: [null, "development", null, null] },
      { name: "Host / open a local app", cells: [null, "released", "released", null] },
      { name: "Cashu & Lightning wallet", cells: ["released", "released", "released", null] },
      { name: "Ark & USDT wallets", cells: ["development", "development", "development", null] },
      { name: "Local profiles", cells: ["development", "development", null, null] },
      { name: "Backups (file, S3)", cells: ["development", "development", null, null] },
      { name: "Identity proofs", cells: ["planned", "planned", "planned", null] },
      { name: "Groups", cells: ["planned", "planned", "planned", null] },
    ] as { name: string; cells: (Level | null)[] }[],
    notes: [
      "Calls are available in chats over the legacy WebRTC profile; paired chats don't have calls yet. Screen sharing needs a computer.",
      "The extension shows the backup screen but runs a single profile; restoring there can't switch to the new profile.",
      "Infrastructure you may touch: public Pkarr relays (browsers), Google STUN servers, Cashu mints, Iroh's n0 relays, HyperDHT's public bootstrap nodes, Ark operators, Ethereum RPCs. No TURN server by default.",
    ],
  },
  next: {
    catalog: { title: "The WISP catalog", body: "Every draft, searchable, with its status and what implements it.", cta: "Open the catalog" },
    roadmap: { title: "The roadmap", body: "What comes next, in order and with dependencies — never with invented dates.", cta: "See the roadmap" },
    docs: { title: "Protocol docs", body: "The long-form protocol walkthrough from the public release.", cta: "Read the docs" },
  },
};

export type DevCopy = typeof en;

const ptBr: DevCopy = {
  meta: {
    title: "Construa com o Ghostly",
    description:
      "Ghost é uma primitiva pequena de encontro sobre Pkarr / DHT Mainline. O Ghostly a compõe com transportes, capacidades e estado local. Leia os contratos WISP, veja código real, construa seu próprio cliente ou adapter.",
  },
  hero: {
    eyebrow: "Para desenvolvedores",
    title1: "O Ghost é pequeno de propósito.",
    title2: "Componha o resto.",
    lead: "Ghost é a primitiva de encontro: pequenos registros assinados no Pkarr e na DHT Mainline, o suficiente para dois peers se acharem e combinarem. O Ghostly é um app de referência que a compõe com transportes, capacidades e estado local. O seu pode ser bem menor.",
    ctaCore: "Ler o contrato do núcleo",
    ctaCatalog: "Ver os {n} WISPs",
    ctaCode: "Código no GitHub",
  },
  words: {
    eyebrow: "01 — Seis palavras",
    title: "O vocabulário, antes do diagrama.",
    lead: "A maior parte da confusão vem de misturar estes termos. WISP não é plugin; perfil de protocolo não é o seu perfil local.",
    items: [
      {
        id: "wisp",
        term: "WISP",
        says: "Uma especificação.",
        body: "Um contrato interoperável que qualquer um pode implementar. Descreve comportamento, não um recurso instalado — e logo nova não precisa de WISP.",
        example: "WISP 500 · Transferência de arquivos",
      },
      {
        id: "capability",
        term: "Capability",
        says: "O que um cliente anuncia.",
        body: "Uma capacidade versionada que um cliente rodando realmente oferece numa sessão. Os dois lados usam só o que ambos anunciam.",
        example: "files/2 · payments-cashu/1",
      },
      {
        id: "adapter",
        term: "Adapter",
        says: "Uma tecnologia, encaixada.",
        body: "Uma implementação de um contrato com uma tecnologia específica. Dois adapters do mesmo contrato não são automaticamente compatíveis entre si.",
        example: "WebRTC (101) · Cashu (201)",
      },
      {
        id: "profile",
        term: "Perfil de protocolo",
        says: "As regras concretas.",
        body: "Uma combinação exata, com amarração de wire, de peças. Não confundir com perfil local, que é onde ficam os dados de uma pessoa no aparelho.",
        example: "Paired Chat (401) ≠ Perfis locais (04)",
      },
      {
        id: "plugin",
        term: "Plugin",
        says: "Uma embalagem possível.",
        body: "Uma forma futura de distribuir adapters, interfaces ou apps. Embalagem, não especificação — e ainda não disponível.",
        example: "planejado",
        level: "planned",
      },
      {
        id: "provider",
        term: "Provider / signer",
        says: "Quem executa ou autoriza.",
        body: "Um serviço ou componente que executa ou aprova uma função específica. Usar a mesma curva de um signer não significa integrar com ele.",
        example: "um mint Cashu · um operador Ark · um RPC Ethereum",
      },
    ],
  },
  compose: {
    eyebrow: "02 — Composição",
    title: "Escolha as peças. Veja o que sai.",
    lead: "Cada bloco é uma peça com o próprio contrato. Escolha uma composição e selecione qualquer bloco para ver o que ele permite e onde está especificado.",
    presets: "Composições",
    selectHint: "Selecione um bloco",
    enables: "O que permite",
    specs: "Especificado em",
    noSpec: "Ainda sem WISP",
    docs: "Referência",
    included: "{n} de {t} peças",
    boardLabel: "Tabuleiro da arquitetura",
  },
  negotiate: {
    eyebrow: "03 — Negociação",
    title: "Dois peers. Uma resposta honesta.",
    lead: "Uma demonstração conceitual da regra das sessões pareadas: cada lado oferece o que tem, na própria ordem; a interseção é ordenada pelas duas ordens juntas. Se não houver nada em comum, a resposta é não.",
    note: "A ordem de transportes usa a mesma regra de packages/core/src/pairedTransports.ts. As capacidades estão simplificadas. Sessões pareadas estão em desenvolvimento.",
    scenarios: "Teste um cenário",
    scenarioNames: {
      match: "Desktop ↔ desktop",
      browser: "Desktop ↔ navegador",
      none: "Sem transporte em comum",
      partial: "Pagamento só de um lado",
    },
    platform: "Roda em",
    platforms: { desktop: "App desktop", browser: "Navegador", extension: "Extensão" },
    transports: "O que oferece, em ordem",
    preferred: "Transporte preferido",
    capabilities: "Capacidades",
    fallback: "Permitir fallback",
    up: "Subir",
    result: "Resultado",
    agreed: "Combinado",
    order: "Tentar nesta ordem",
    off: "Fica desligado",
    fail: "Sem transporte em comum. Sem conexão — e nada faz ponte automática entre WebRTC e Iroh. Uma ponte seria uma integração própria, com a própria confiança.",
    noFallback: "O fallback está desligado de um lado, então só a primeira opção é tentada.",
    offer: "O que o Boo envia (formato de um pair-offer real)",
    boo: "Boo",
    casper: "Casper",
    unavailable: "indisponível nesta plataforma",
  },
  path: {
    eyebrow: "04 — Seu caminho",
    title: "Da leitura à construção.",
    lead: "Arquivos reais, comandos reais. Nada aqui é um SDK que ainda não escrevemos.",
    steps: [
      {
        title: "Entenda o núcleo",
        body: "Como dois peers se encontram: registros Pkarr assinados, pacotes de 1000 bytes, TTL de 300 segundos.",
        links: [
          { label: "WISP 01 · Ghost Core", href: "/pt-br/developers/wisps/01-ghost-core" },
          { label: "O protocolo Ghost", href: "/pt-br/developers/wisps/protocol" },
        ],
      },
      {
        title: "Leia um contrato",
        body: "Comece por uma família: chat, arquivos ou pagamentos. Cada contrato lista seus adapters e perfis.",
        links: [
          { label: "WISP 400 · Chat", href: "/pt-br/developers/wisps/400-chat" },
          { label: "WISP 100 · Transportes", href: "/pt-br/developers/wisps/100-transports" },
        ],
      },
      {
        title: "Veja uma implementação real",
        body: "O núcleo em TypeScript, os transportes nativos e a CLI em Rust estão todos no repositório.",
        code: "packages/core/src/invite.ts",
        links: [
          { label: "packages/core", href: "https://github.com/MiguelMedeiros/ghostly/tree/dev/packages/core/src" },
          { label: "native-transports", href: "https://github.com/MiguelMedeiros/ghostly/tree/dev/native-transports" },
          { label: "cli", href: "https://github.com/MiguelMedeiros/ghostly/tree/dev/cli" },
        ],
      },
      {
        title: "Construa um cliente ou adapter",
        body: "A CLI é um cliente pequeno e completo: identidade, convite, envio e um fluxo JSON. Automatize com ela ou implemente os mesmos contratos na sua linguagem.",
        links: [{ label: "Guia da CLI (em inglês)", href: "/cli" }],
      },
      {
        title: "Contribua",
        body: "Proponha mudanças num rascunho, relate o que não bateu ou adicione um adapter. Um Draft só vira Final com duas implementações independentes.",
        links: [
          { label: "WISP 00 · Processo", href: "/pt-br/developers/wisps/00-process" },
          { label: "Como contribuir", href: "/pt-br/developers/wisps/contributing" },
        ],
      },
    ],
    codeCaption: "De packages/core/src/invite.ts — as duas pontas de um link nascem juntas.",
  },
  availability: {
    eyebrow: "05 — Onde roda",
    title: "Cliente por cliente.",
    lead: "O mesmo recurso pode existir num cliente e não em outro. Este é o mapa honesto.",
    feature: "Recurso",
    clients: ["App web", "Desktop", "Extensão", "CLI"],
    none: "—",
    rows: [
      { name: "Chat de texto", cells: ["released", "released", "released", "released"] },
      { name: "Chats pareados, chaves fixadas", cells: ["development", "development", "development", null] },
      { name: "Arquivos (100 MiB)", cells: ["released", "released", "released", null] },
      { name: "Voz, vídeo, tela", cells: ["released", "released", "released", null] },
      { name: "Iroh e HyperDHT", cells: [null, "development", null, null] },
      { name: "Hospedar / abrir app local", cells: [null, "released", "released", null] },
      { name: "Carteira Cashu e Lightning", cells: ["released", "released", "released", null] },
      { name: "Carteiras Ark e USDT", cells: ["development", "development", "development", null] },
      { name: "Perfis locais", cells: ["development", "development", null, null] },
      { name: "Backups (arquivo, S3)", cells: ["development", "development", null, null] },
      { name: "Provas de identidade", cells: ["planned", "planned", "planned", null] },
      { name: "Grupos", cells: ["planned", "planned", "planned", null] },
    ],
    notes: [
      "Chamadas existem nos chats do perfil WebRTC legado; os chats pareados ainda não têm chamadas. Compartilhar a tela exige um computador.",
      "A extensão mostra a tela de backup, mas roda um único perfil; restaurar ali não troca para o perfil novo.",
      "Infraestrutura que você pode tocar: relays públicos do Pkarr (navegadores), servidores STUN do Google, mints Cashu, relays n0 do Iroh, nós públicos de bootstrap da HyperDHT, operadores Ark, RPCs Ethereum. Sem servidor TURN por padrão.",
    ],
  },
  next: {
    catalog: { title: "O catálogo de WISPs", body: "Todos os rascunhos, com busca, status e o que os implementa.", cta: "Abrir o catálogo" },
    roadmap: { title: "O roadmap", body: "O que vem a seguir, em ordem e com dependências — nunca com datas inventadas.", cta: "Ver o roadmap" },
    docs: { title: "Docs do protocolo", body: "O passo a passo longo do protocolo da versão pública (em inglês).", cta: "Ler os docs" },
  },
};

export const developers: Localized<DevCopy> = { en, "pt-br": ptBr };
