import type { Localized } from "@/lib/i18n";
import type { Level } from "@/lib/status";

const A: Level = "available";

const en = {
  meta: {
    title: "Build with Ghostly",
    description:
      "Ghost is a small rendezvous primitive on Pkarr / Mainline DHT. Ghostly composes it with transports, capabilities and local state. Read the WISP contracts, see real code, build your own client or adapter.",
  },
  hero: {
    eyebrow: "For developers",
    title: "Two peers. A DHT. A direct line.",
    lead: "Each app publishes a small signed record to the Mainline DHT, finds the other's, keeps what both speak and opens a direct connection. Every step is an open contract, a WISP.",
    ctaCore: "WISP 01 · Ghost Core",
    ctaCatalog: "Browse {n} WISPs",
    ctaCode: "GitHub",
    loop: {
      label:
        "Looping diagram. Your app and Ghostly desktop each publish a small signed record to Pkarr and the Mainline DHT (WISP 01) and find each other's. They exchange capability offers and keep only what both have (WISP 03), open a direct WebRTC line (WISP 100 to 102) and send a message, a file and a payment over it (WISP 400, 500 and 200). Hover or focus pauses it.",
      left: "your app",
      right: "Ghostly desktop",
      dht: "Pkarr · Mainline DHT",
      spec: "≤ 1000 B · TTL 300 s",
      record: "signed",
      phases: {
        publish: "Publish a signed record",
        find: "Find each other",
        offer: "Match the offers",
        connect: "Open a direct line",
        talk: "Chat, files, payments",
        done: "Every session, four steps",
      },
      stack: { rendezvous: "rendezvous", negotiate: "negotiate", connect: "connect", talk: "talk" },
      firstPairing: "first pairing",
      later: "desktops, later: iroh/1",
      packets: { message: "hi!", file: "notes.pdf", payment: "2,100 sat", mint: "mint" },
    },
  },
  compose: {
    eyebrow: "01 · Composition",
    title: "Pick the pieces. See what you get.",
    lead: "Each row is an area of the architecture, each block a piece with its own contract. Pick a composition: it lights the pieces it needs.",
    presets: "Compositions",
    selectHint: "Tap a block for what it does and the WISP that specifies it.",
    close: "Close",
    enables: "What it enables",
    specs: "Specified in",
    noSpec: "No WISP yet",
    docs: "Reference",
    included: "{n} of {t} pieces",
    boardLabel: "Architecture board",
  },
  negotiate: {
    eyebrow: "02 · Negotiation",
    title: "Two peers. One honest answer.",
    lead: "Each side offers what it has, in its own order. What both have is ranked by both orders together. Nothing in common means no.",
    scenarios: "Scenario",
    scenarioNames: {
      match: "Desktop ↔ desktop",
      browser: "Desktop ↔ browser",
      none: "No common transport",
      partial: "Payments on one side",
    },
    captions: {
      match: "A tie at 3: the fixed order breaks it, iroh first.",
      browser: "The browser speaks only WebRTC. Arkade is off on Casper's side.",
      none: "Fallback is off on the desktop, so it offers Iroh alone.",
      partial: "Chat and files go ahead; Cashu stays off.",
    },
    phases: {
      offers: "Offers go out",
      ranked: "Transports ranked",
      agreed: "Capabilities agreed",
      nothing: "Nothing in common",
      none: "No connection",
    },
    platforms: { desktop: "Desktop app", browser: "Browser" },
    tags: { fallbackOff: "fallback off", arkadeOff: "Arkade off", paymentsOff: "payments off" },
    transports: "Transports, in order",
    capabilities: "Capabilities",
    result: "Result",
    comparing: "Comparing offers…",
    agreed: "Agreed",
    order: "Try in this order",
    sum: "position on Boo's list + position on Casper's list; lower wins",
    off: "Stays off",
    fail: "No connection",
    failBody: "Nothing in common. Nothing bridges WebRTC to Iroh; a bridge would be its own integration, with its own trust.",
    first: "The very first pairing always runs over WebRTC. That is how the peers learn each other's native addresses. The ranking applies from the second session on.",
    rule: "Same rule as rankTransports() in packages/core/src/pairedTransports.ts",
    simplified: "offers simplified",
    status: "Paired chats: web, desktop and extension",
    boo: "Boo",
    casper: "Casper",
  },
  path: {
    eyebrow: "03 · Your path",
    title: "From reading to building.",
    steps: [
      {
        title: "Understand the core",
        body: "Signed Pkarr records: at most 1000 bytes, a 300-second TTL.",
        links: [
          { label: "WISP 01 · Ghost Core", href: "/developers/wisps/01-ghost-core" },
          { label: "The Ghost Protocol", href: "/developers/wisps/protocol" },
        ],
      },
      {
        title: "Read a contract",
        body: "Pick one family: chat, files or payments.",
        links: [
          { label: "WISP 400 · Chat", href: "/developers/wisps/400-chat" },
          { label: "WISP 500 · Files", href: "/developers/wisps/500-files" },
          { label: "WISP 200 · Payments", href: "/developers/wisps/200-payments" },
        ],
      },
      {
        title: "Build a client or adapter",
        body: "The protocol library, the SDK, the native transports and a Rust CLI.",
        links: [
          { label: "packages/core", href: "https://github.com/MiguelMedeiros/ghostly/tree/dev/packages/core/src" },
          { label: "packages/sdk", href: "https://github.com/MiguelMedeiros/ghostly/tree/dev/packages/sdk" },
          { label: "native-transports", href: "https://github.com/MiguelMedeiros/ghostly/tree/dev/native-transports" },
          { label: "cli", href: "https://github.com/MiguelMedeiros/ghostly/tree/dev/cli" },
          { label: "CLI guide", href: "/cli" },
        ],
      },
    ],
  },
  availability: {
    eyebrow: "04 · Where it runs",
    title: "Client by client.",
    lead: "The same feature can be available in one client and not another. This is the honest map.",
    feature: "Feature",
    clients: ["Web app", "Desktop", "Extension", "CLI"],
    none: "No",
    rows: [
      { name: "Text chat", cells: [A, A, A, A] },
      { name: "Paired chats, pinned keys", cells: [A, A, A, null] },
      { name: "Files (100 MiB)", cells: [A, A, A, null] },
      { name: "Voice messages", cells: [A, A, A, null] },
      { name: "Voice, video, screen", cells: [A, A, A, null] },
      { name: "Iroh & HyperDHT (HyperDHT not yet on Intel Macs)", cells: [null, A, null, null] },
      { name: "Host / open a local app", cells: [null, A, A, null] },
      { name: "Cashu & Lightning wallet", cells: [A, A, A, null] },
      { name: "Your own Lightning source (NWC, LND, CLN, WebLN, Breez, Fedimint)", cells: [A, A, A, null] },
      { name: "Lightning addresses, paying from another wallet", cells: [A, A, A, null] },
      { name: "Ark (Arkade, Bark), Spark, Fedimint & USDT wallets", cells: [A, A, A, null] },
      { name: "On-chain bitcoin (BDK, Bitcoin Core)", cells: [A, A, A, null] },
      { name: "Local profiles", cells: [A, A, A, null] },
      { name: "Backups (file, S3)", cells: [A, A, A, null] },
      { name: "Messages held for an away contact (your S3)", cells: [A, A, A, null] },
      { name: "Identity proofs (Nostr, domain, OpenPGP, SSH, Bitcoin)", cells: [A, A, A, null] },
      { name: "Nostr social layer (profile, follows, notes)", cells: [A, A, A, null] },
      { name: "Private groups (up to 8) and communities (up to 256)", cells: [A, A, A, null] },
      { name: "Payments in groups", cells: [A, A, A, null] },
    ] as { name: string; cells: (Level | null)[] }[],
    notes: [
      "Calls: WebRTC chats only, not paired chats or groups. Groups: text, a picture and payments; no files or calls. CLI: legacy DHT text, keys passed by hand. Desktop on Linux: its webview has no WebRTC, so no live link there yet.",
      "WebLN is web-only, Bitcoin Core desktop-only. Bark, BDK, Breez and Fedimint run on test networks only; Spark needs your own Breez API key for Mainnet. OpenID waits for OAuth clients.",
      "Also contacted: Pkarr relays, Google STUN, mints, Iroh relays, HyperDHT bootstrap nodes, Ark and Spark operators, Fedimint guardians, Esplora servers, Nostr relays, Ethereum RPCs, and any service you add. No TURN by default.",
    ],
  },
  next: {
    catalog: { title: "The WISP catalog", body: "Every WISP, searchable, with its status and implementations.", cta: "Open the catalog" },
    roadmap: { title: "The roadmap", body: "What comes next, in dependency order. No dates.", cta: "See the roadmap" },
    docs: { title: "Protocol docs", body: "The long-form walkthrough of the protocol.", cta: "Read the docs" },
  },
};

export type DevCopy = typeof en;

const ptBr: DevCopy = {
  meta: {
    title: "Construa com o Ghostly",
    description:
      "Ghost é uma primitiva pequena de encontro sobre Pkarr / DHT Mainline. O Ghostly a compõe com transportes, capacidades e estado local. Leia os contratos WISP, veja código real, construa seu próprio cliente ou adapter.",
  },
  hero: {
    eyebrow: "Para desenvolvedores",
    title: "Dois peers. Uma DHT. Uma linha direta.",
    lead: "Cada app publica um pequeno registro assinado na DHT Mainline, acha o do outro, fica com o que os dois falam e abre uma conexão direta. Cada passo é um contrato aberto, um WISP.",
    ctaCore: "WISP 01 · Ghost Core",
    ctaCatalog: "Ver os {n} WISPs",
    ctaCode: "GitHub",
    loop: {
      label:
        "Diagrama em loop. O seu app e o Ghostly desktop publicam cada um um pequeno registro assinado no Pkarr e na DHT Mainline (WISP 01) e acham o do outro. Trocam ofertas de capacidades e ficam só com o que os dois têm (WISP 03), abrem uma linha WebRTC direta (WISP 100 a 102) e mandam por ela uma mensagem, um arquivo e um pagamento (WISP 400, 500 e 200). Passar o mouse ou focar pausa o loop.",
      left: "seu app",
      right: "Ghostly desktop",
      dht: "Pkarr · DHT Mainline",
      spec: "≤ 1000 B · TTL 300 s",
      record: "assinado",
      phases: {
        publish: "Publicar um registro assinado",
        find: "Achar um ao outro",
        offer: "Cruzar as ofertas",
        connect: "Abrir uma linha direta",
        talk: "Chat, arquivos, pagamentos",
        done: "Toda sessão, quatro passos",
      },
      stack: { rendezvous: "encontro", negotiate: "negociação", connect: "conexão", talk: "conversa" },
      firstPairing: "primeiro pareamento",
      later: "desktops, depois: iroh/1",
      packets: { message: "oi!", file: "notas.pdf", payment: "2.100 sat", mint: "mint" },
    },
  },
  compose: {
    eyebrow: "01 · Composição",
    title: "Escolha as peças. Veja o que sai.",
    lead: "Cada linha é uma área da arquitetura; cada bloco, uma peça com o próprio contrato. Escolha uma composição: ela acende as peças de que precisa.",
    presets: "Composições",
    selectHint: "Toque num bloco para ver o que ele faz e a WISP que o especifica.",
    close: "Fechar",
    enables: "O que permite",
    specs: "Especificado em",
    noSpec: "Ainda sem WISP",
    docs: "Referência",
    included: "{n} de {t} peças",
    boardLabel: "Tabuleiro da arquitetura",
  },
  negotiate: {
    eyebrow: "02 · Negociação",
    title: "Dois peers. Uma resposta honesta.",
    lead: "Cada lado oferece o que tem, na própria ordem. O que os dois têm é ordenado pelas duas ordens juntas. Nada em comum quer dizer não.",
    scenarios: "Cenário",
    scenarioNames: {
      match: "Desktop ↔ desktop",
      browser: "Desktop ↔ navegador",
      none: "Sem transporte em comum",
      partial: "Pagamento só de um lado",
    },
    captions: {
      match: "Empate em 3: a ordem fixa desempata, iroh primeiro.",
      browser: "O navegador só fala WebRTC. Arkade está desligado do lado do Casper.",
      none: "O desktop está sem fallback, então oferece só Iroh.",
      partial: "Chat e arquivos seguem; Cashu fica de fora.",
    },
    phases: {
      offers: "Ofertas enviadas",
      ranked: "Transportes ordenados",
      agreed: "Capacidades combinadas",
      nothing: "Nada em comum",
      none: "Sem conexão",
    },
    platforms: { desktop: "App desktop", browser: "Navegador" },
    tags: { fallbackOff: "sem fallback", arkadeOff: "Arkade desligado", paymentsOff: "pagamentos desligados" },
    transports: "Transportes, em ordem",
    capabilities: "Capacidades",
    result: "Resultado",
    comparing: "Comparando ofertas…",
    agreed: "Combinado",
    order: "Tentar nesta ordem",
    sum: "posição na lista do Boo + posição na lista do Casper; menor vence",
    off: "Fica de fora",
    fail: "Sem conexão",
    failBody: "Nada em comum. Nada faz ponte entre WebRTC e Iroh; uma ponte seria uma integração própria, com a própria confiança.",
    first: "O primeiro pareamento sempre roda por WebRTC: é assim que os peers aprendem os endereços nativos um do outro. A ordem vale a partir da segunda sessão.",
    rule: "A mesma regra de rankTransports() em packages/core/src/pairedTransports.ts",
    simplified: "ofertas simplificadas",
    status: "Chats pareados: web, desktop e extensão",
    boo: "Boo",
    casper: "Casper",
  },
  path: {
    eyebrow: "03 · Seu caminho",
    title: "Da leitura à construção.",
    steps: [
      {
        title: "Entenda o núcleo",
        body: "Registros Pkarr assinados: no máximo 1000 bytes, TTL de 300 segundos.",
        links: [
          { label: "WISP 01 · Ghost Core", href: "/pt-br/developers/wisps/01-ghost-core" },
          { label: "O protocolo Ghost", href: "/pt-br/developers/wisps/protocol" },
        ],
      },
      {
        title: "Leia um contrato",
        body: "Escolha uma família: chat, arquivos ou pagamentos.",
        links: [
          { label: "WISP 400 · Chat", href: "/pt-br/developers/wisps/400-chat" },
          { label: "WISP 500 · Arquivos", href: "/pt-br/developers/wisps/500-files" },
          { label: "WISP 200 · Pagamentos", href: "/pt-br/developers/wisps/200-payments" },
        ],
      },
      {
        title: "Construa um cliente ou adapter",
        body: "A biblioteca do protocolo, o SDK, os transportes nativos e uma CLI em Rust.",
        links: [
          { label: "packages/core", href: "https://github.com/MiguelMedeiros/ghostly/tree/dev/packages/core/src" },
          { label: "packages/sdk", href: "https://github.com/MiguelMedeiros/ghostly/tree/dev/packages/sdk" },
          { label: "native-transports", href: "https://github.com/MiguelMedeiros/ghostly/tree/dev/native-transports" },
          { label: "cli", href: "https://github.com/MiguelMedeiros/ghostly/tree/dev/cli" },
          { label: "Guia da CLI (em inglês)", href: "/cli" },
        ],
      },
    ],
  },
  availability: {
    eyebrow: "04 · Onde roda",
    title: "Cliente por cliente.",
    lead: "O mesmo recurso pode existir num cliente e não em outro. Este é o mapa honesto.",
    feature: "Recurso",
    clients: ["App web", "Desktop", "Extensão", "CLI"],
    none: "Não",
    rows: [
      { name: "Chat de texto", cells: [A, A, A, A] },
      { name: "Chats pareados, chaves fixadas", cells: [A, A, A, null] },
      { name: "Arquivos (100 MiB)", cells: [A, A, A, null] },
      { name: "Mensagens de voz", cells: [A, A, A, null] },
      { name: "Voz, vídeo, tela", cells: [A, A, A, null] },
      { name: "Iroh e HyperDHT (HyperDHT ainda não em Macs Intel)", cells: [null, A, null, null] },
      { name: "Hospedar / abrir app local", cells: [null, A, A, null] },
      { name: "Carteira Cashu e Lightning", cells: [A, A, A, null] },
      { name: "Sua própria fonte Lightning (NWC, LND, CLN, WebLN, Breez, Fedimint)", cells: [A, A, A, null] },
      { name: "Lightning addresses, pagar com outra carteira", cells: [A, A, A, null] },
      { name: "Carteiras Ark (Arkade, Bark), Spark, Fedimint e USDT", cells: [A, A, A, null] },
      { name: "Bitcoin on-chain (BDK, Bitcoin Core)", cells: [A, A, A, null] },
      { name: "Perfis locais", cells: [A, A, A, null] },
      { name: "Backups (arquivo, S3)", cells: [A, A, A, null] },
      { name: "Mensagens guardadas para um contato ausente (seu S3)", cells: [A, A, A, null] },
      { name: "Provas de identidade (Nostr, domínio, OpenPGP, SSH, Bitcoin)", cells: [A, A, A, null] },
      { name: "Camada social do Nostr (perfil, quem segue, notas)", cells: [A, A, A, null] },
      { name: "Grupos privados (até 8) e comunidades (até 256)", cells: [A, A, A, null] },
      { name: "Pagamentos em grupos", cells: [A, A, A, null] },
    ],
    notes: [
      "Chamadas: só em chats WebRTC, não em pareados nem grupos. Grupos: texto, uma foto e pagamentos; sem arquivos nem chamadas. CLI: texto legado pela DHT, chaves à mão. Desktop no Linux: o webview não tem WebRTC, então ainda sem link ao vivo lá.",
      "WebLN só na web, Bitcoin Core só no desktop. Bark, BDK, Breez e Fedimint só em redes de teste; o Spark exige a sua própria chave de API da Breez na Mainnet. OpenID espera os clientes OAuth.",
      "Também contatados: relays Pkarr, STUN do Google, mints, relays Iroh, nós de bootstrap da HyperDHT, operadores Ark e Spark, guardiões Fedimint, servidores Esplora, relays Nostr, RPCs Ethereum e o serviço que você adicionar. Sem TURN por padrão.",
    ],
  },
  next: {
    catalog: { title: "O catálogo de WISPs", body: "Todos os WISPs, com busca, status e implementações.", cta: "Abrir o catálogo" },
    roadmap: { title: "O roadmap", body: "O que vem depois, na ordem das dependências, sem datas.", cta: "Ver o roadmap" },
    docs: { title: "Docs do protocolo", body: "O passo a passo longo do protocolo (em inglês).", cta: "Ler os docs" },
  },
};

export const developers: Localized<DevCopy> = { en, "pt-br": ptBr };
