import type { Localized } from "@/lib/i18n";
import type { Level } from "@/lib/status";

/**
 * Homepage copy. Every capability claim was checked against the code:
 * "released" = v0.4.0 on `main`; "development" = merged on `dev` for 0.5.0.
 */
const en = {
  meta: {
    title: "Ghostly — Find each other. Talk peer to peer.",
    description:
      "Meet the people you choose through a private invitation, then chat, send files and sats, peer to peer. No account to create. Free and open source.",
  },
  rail: "Where you are in the story",
  hero: {
    badge: "Peer to peer · No account to create",
    title1: "Find your people.",
    title2: "Talk peer to peer.",
    lead: "Ghostly connects you straight to the people you invite — to chat, send files and sats, call, and share what runs on your computer.",
    open: "Open in your browser",
    download: "Download the app",
    micro: "Nothing to install · Free and open source",
    follow: "Follow Boo",
    booSays: "Is anyone out there?",
    skip: "Skip the story",
  },
  statement: {
    // The last sentence of dht.steps[0].body, given the whole screen between the acts.
    before: "There is ",
    accent: "no",
    after: " Ghostly server in the middle.",
  },
  invite: {
    eyebrow: "01 — The invitation",
    label: "How an invitation works",
    steps: [
      {
        title: "Create an invitation.",
        body: "Boo makes an invitation for one person. It holds the keys for this connection — nothing about a public account, because there isn't one.",
      },
      {
        title: "Share it your way.",
        body: "As a link, a QR code or a text code — in person, by message, however you like. Only share it with the person you want to meet.",
        note: "Links work in the current release. Scanning a QR code with the camera arrives with the next one.",
      },
      {
        title: "Connect.",
        body: "Casper opens it, both apps find each other, and the two of you confirm the connection. That's it. You're talking.",
      },
    ],
    card: { title: "Invitation", link: "Link", qr: "QR", code: "Code", forOne: "for one person" },
  },
  dht: {
    eyebrow: "02 — The meeting place",
    label: "How the two apps find each other on the DHT",
    steps: [
      {
        title: "A public network with no owner.",
        body: "To find each other, both apps use the Mainline DHT — millions of computers that already help BitTorrent users meet — through Pkarr. There is no Ghostly server in the middle.",
        note: "Browsers reach the DHT through public Pkarr relays; the desktop app and CLI can also reach it directly.",
      },
      {
        title: "Small, signed, sealed notes.",
        body: "Boo leaves a few tiny records at different places in the network. Each is signed, and what matters inside is encrypted. They are notes, not a mailbox: under a kilobyte each.",
      },
      {
        title: "Only the invitation opens them.",
        body: "Casper knows where to look and how to read, because the invitation says so. Anyone else passing by sees sealed records they can't interpret.",
      },
      {
        title: "Then they fade.",
        body: "Records are republished while you're online. When you stop, nothing refreshes them: they age out of the network and the apps stop accepting old ones. That doesn't erase copies someone may already have made, or the history on your own device.",
      },
    ],
    tags: { sealed: "sealed", ttl: "expires" },
  },
  agree: {
    eyebrow: "03 — The agreement",
    label: "How both sides agree on what to use",
    steps: [
      {
        title: "Each side says what it can do.",
        body: "Boo's desktop app and Casper's browser each list the abilities they support, with versions, and the paths they prefer.",
      },
      {
        title: "They keep what they share.",
        body: "Not a lottery, not magic: only what appears on both lists is used. What one side lacks simply stays off.",
      },
      {
        title: "A plan both agreed to.",
        body: "Chat, files and Cashu, over WebRTC — because that's what these two have in common. Change the apps, and the plan changes with them.",
        note: "Negotiated abilities come with paired chats, in the next release. Chats in the current release use a fixed set.",
      },
    ],
    boo: "Boo · desktop",
    casper: "Casper · browser",
    plan: "The plan",
  },
  alive: {
    eyebrow: "04 — The connection comes alive",
    label: "How the conversation leaves the DHT for a direct connection",
    steps: [
      {
        title: "The DHT only introduced them.",
        body: "Rendezvous records are small on purpose. Once Boo and Casper know how to reach each other, the conversation moves off them.",
      },
      {
        title: "A direct line for the real conversation.",
        body: "Messages, files and payments travel over a live connection between the two devices: WebRTC in the web app, extension and desktop, and Iroh or HyperDHT between desktop apps in the next release. Calls use WebRTC media.",
      },
      {
        title: "Honest about the route.",
        body: "Public STUN servers help the two devices find a route through home routers. If a direct path isn't possible, the connection can fail — you can add your own TURN relay in settings.",
        note: "Very short texts can still travel as DHT records when no live link is up — up to 500 bytes today, 256 bytes in paired chats.",
      },
    ],
    pipe: "live connection",
    thread: "rendezvous",
  },
  next: {
    eyebrow: "05 — What happens next",
    title: "Now that you're connected.",
    lead: "Everything here is in the current release, unless the badge says otherwise.",
    shot: "Screenshot of the Ghostly app",
    illustration: "Illustration",
    fromDev: "Development build, {n}",
    fromOld: "An earlier build",
    items: [
      {
        id: "chat",
        icon: "chat",
        title: "Say it your way.",
        body: "Private one-to-one conversations with delivery receipts and local history. No phone number, no public profile.",
        level: "released" as Level,
        extra: "Paired chats — with pinned keys, names and pictures — are in development.",
        extraLevel: "development" as Level,
      },
      {
        id: "files",
        icon: "file",
        title: "Send the actual thing.",
        body: "Photos, documents, projects: straight from your device to theirs, checked on arrival.",
        level: "released" as Level,
        extra: "Up to 100 MiB per file, with both of you online.",
      },
      {
        id: "calls",
        icon: "video",
        title: "Be a little closer.",
        body: "Voice, video and screen sharing, one to one.",
        level: "released" as Level,
        extra: "In chats over WebRTC. Screen sharing needs a computer. Paired chats don't have calls yet.",
      },
      {
        id: "sats",
        icon: "bolt",
        title: "A little thank-you.",
        body: "Send or request sats right in the conversation, as Cashu ecash or a Lightning invoice.",
        level: "released" as Level,
        extra: "A Cashu mint you choose holds the funds and handles Lightning. Pick one you trust.",
      },
      {
        id: "identities",
        icon: "badge",
        title: "Prove who you are. Only to whom you choose.",
        body: "Attach an outside identity to your profile once — a Nostr key, a domain, an OpenPGP or SSH key, a Bitcoin address — and share it with one contact at a time. Their app verifies it on the device.",
        level: "development" as Level,
        extra: "Never required to talk. Withdraw it per contact, or revoke it everywhere. Accounts at Google, Microsoft, Apple, GitLab or Twitch are merged but wait for registered clients.",
      },
      {
        id: "services",
        icon: "window",
        title: "Made here. Open there.",
        body: "Let a contact open a web app running on your computer — a photo gallery, a dashboard, a prototype — while you're online.",
        level: "released" as Level,
        extra: "Desktop app or browser extension at both ends. Plain HTTP requests: no WebSockets or streaming. Choosing exactly which contacts see each app is in development.",
      },
      {
        id: "cli",
        icon: "terminal",
        title: "Give your code a voice.",
        body: "A command-line client for scripts, bots and agents: create an identity and invitations, send, receive and watch a chat as a JSON stream.",
        level: "released" as Level,
        extra: "Text messages only. Its invitations are for other CLI peers; talking to the app means passing the keys by hand.",
        link: { label: "CLI guide", href: "/cli" },
      },
    ],
  },
  space: {
    eyebrow: "06 — Your space",
    title: "Everything stays yours, on your device.",
    lead: "Chats, keys, wallets and services live in the app. No server of ours.",
    profiles: {
      title: "Separate lives, one device.",
      level: "development" as Level,
      note: "Contacts never learn the others exist · web and desktop; the extension runs one profile",
      names: ["Personal", "Work", "Club"],
    },
    backup: {
      title: "Backup is what. Storage is where.",
      level: "development" as Level,
      what: "Backup",
      where: "Storage",
      whatItems: ["chats & keys", "wallets", "services", "settings"],
      whereItems: ["a file you keep", "S3 · R2 · B2 · MinIO"],
      note: "Sealed with your passphrase · restoring creates a new profile, nothing is overwritten",
    },
    look: {
      title: "Make it look like you.",
      level: "released" as Level,
      note: "Four themes · light or dark · eight languages · app lock",
    },
  },
  wallets: {
    title: "One wallet, many ways to pay.",
    lead: "Each payment method is its own card, with its own rules. Pick one to see what it does and how ready it is.",
    hint: "Choose a card",
    testnet: "A Testnet switch moves every wallet to test networks at once — in development.",
    cards: [
      {
        id: "cashu",
        name: "Cashu",
        kind: "ecash",
        level: "released" as Level,
        body: "Private ecash tokens you can pass along in a chat. A mint you choose holds the funds.",
        limits: "Trust the mint you pick: it can see its own operations and holds the backing sats.",
      },
      {
        id: "lightning",
        name: "Lightning",
        kind: "invoices",
        level: "released" as Level,
        body: "Pay and receive Lightning invoices from the chat.",
        limits: "Through your Cashu mint in the current release. In the next one your own node or wallet can be the source: NWC, LND, Core Lightning, a browser wallet (WebLN, web app only) or Breez on a local regtest.",
        more: "development" as Level,
      },
      {
        id: "ark",
        name: "Ark",
        kind: "via Arkade",
        level: "development" as Level,
        body: "Review and approve an exact Ark payment through a pinned operator.",
        limits: "Experimental. New profiles get a Bitcoin mainnet Ark wallet automatically, but payment flows were exercised only on a local test network; leaving Ark on your own is still a release gate.",
      },
      {
        id: "bark",
        name: "Bark",
        kind: "Second's Ark",
        level: "development" as Level,
        body: "A second Ark provider beside Arkade: same idea, another server, its own way of paying.",
        limits: "Experimental, test networks only (Second's signet server or a local regtest); Mainnet makes no Bark wallet yet. Not interchangeable with Arkade: a Bark wallet cannot pay an Arkade address.",
      },
      {
        id: "usdt",
        name: "USDT",
        kind: "Tether WDK",
        level: "development" as Level,
        body: "Receive and send USDT on Ethereum, signed on your device.",
        limits: "Experimental. Payment flows were validated on a local test chain, not with real funds. Ethereum only; a Sepolia test mode exists.",
      },
      {
        id: "onchain",
        name: "Bitcoin",
        kind: "on-chain",
        level: "development" as Level,
        body: "Plain on-chain bitcoin in a chat, through a BDK wallet or your own Bitcoin Core node.",
        limits: "Experimental. BDK on signet, Mutinynet or regtest only; Bitcoin Core needs the desktop app. On-chain payments are offered only inside an open paired session.",
      },
    ],
  },
  open: {
    eyebrow: "07 — Under the ghosts",
    label: "The pieces that make Ghostly",
    steps: [
      {
        title: "Everything you just saw…",
        body: "…is one app composing independent pieces: a small rendezvous core, transports, and abilities like chat, files and payments.",
      },
      {
        title: "…is built from open pieces.",
        body: "Each piece is described in a WISP, a public draft contract. Another app can implement only the pieces it needs and still meet Ghostly halfway.",
      },
    ],
    layers: ["Ghost · rendezvous & keys", "Transports", "Chat · files · calls", "Payments · services", "Identity proofs · optional", "Profiles · backup · storage", "Your app"],
    cta: "Build with Ghostly",
    catalog: "Browse the WISPs",
  },
  finale: {
    eyebrow: "08 — Your turn",
    title1: "One little step.",
    title2: "You're a ghost.",
    lead: "Open Ghostly in your browser and invite someone you know. Or take it with you on your desktop.",
    browser: {
      title: "In your browser",
      body: "Nothing to install. Open a tab and create an invitation.",
      cta: "Open app.ghostly.tools",
    },
    desktop: {
      title: "For your computer",
      body: "The desktop app for macOS, Windows and Linux — the same Ghostly, installed.",
      platforms: {
        mac: { name: "macOS", chip: "For this Mac" },
        windows: { name: "Windows", chip: "For this PC" },
        linux: { name: "Linux", chip: "For this machine" },
      },
      installers: {
        macArm: "Apple silicon",
        macIntel: "Intel",
        windowsExe: "Setup",
        windowsMsi: "Package",
        linuxDeb: "Debian / Ubuntu",
        linuxAppImage: "Any distro",
      },
    },
    extension: {
      title: "Browser extension",
      body: "Chrome and Chromium browsers, as a .zip to load unpacked.",
      cta: "Download",
    },
    cli: { title: "Command line", body: "For scripts, bots and agents.", cta: "CLI guide" },
    note: "Downloads are the public release, v{v}. Features marked “in development” arrive with {n}.",
    all: "All release files",
    conversation: [
      { side: "boo", text: "Boo! 👻" },
      { side: "casper", text: "Found you." },
      { side: "boo", text: "Wanna see my app?" },
      { side: "casper", text: "It's on your localhost…" },
      { side: "boo", text: "Not anymore ✨" },
      { side: "casper", text: "Here, 21 sats ⚡" },
      { side: "boo", text: "See you around." },
      { side: "casper", text: "*poof* 👻" },
    ],
  },
};

export type HomeCopy = typeof en;

const ptBr: HomeCopy = {
  meta: {
    title: "Ghostly — Encontre quem você quer. Converse direto, peer to peer.",
    description:
      "Encontre as pessoas que você escolher por um convite privado e converse, envie arquivos e sats, peer to peer. Sem criar conta. Gratuito e de código aberto.",
  },
  rail: "Onde você está na história",
  hero: {
    badge: "Peer to peer · Sem criar conta",
    title1: "Encontre sua gente.",
    title2: "Converse direto.",
    lead: "O Ghostly liga você diretamente às pessoas que você convida — para conversar, mandar arquivos e sats, fazer chamadas e compartilhar o que roda no seu computador.",
    open: "Abrir no navegador",
    download: "Baixar o app",
    micro: "Nada para instalar · Gratuito e de código aberto",
    follow: "Siga o Boo",
    booSays: "Tem alguém aí?",
    skip: "Pular a história",
  },
  statement: {
    before: "",
    accent: "Não há",
    after: " um servidor do Ghostly no meio.",
  },
  invite: {
    eyebrow: "01 — O convite",
    label: "Como funciona um convite",
    steps: [
      {
        title: "Crie um convite.",
        body: "O Boo cria um convite para uma pessoa. Ele guarda as chaves desta conexão — nada de conta pública, porque não existe uma.",
      },
      {
        title: "Compartilhe do seu jeito.",
        body: "Como link, QR code ou código de texto — pessoalmente, por mensagem, como preferir. Compartilhe só com quem você quer encontrar.",
        note: "Links funcionam na versão atual. Escanear um QR code com a câmera chega na próxima.",
      },
      {
        title: "Conecte.",
        body: "O Casper abre o convite, os dois apps se encontram e vocês confirmam a conexão. Pronto. Já estão conversando.",
      },
    ],
    card: { title: "Convite", link: "Link", qr: "QR", code: "Código", forOne: "para uma pessoa" },
  },
  dht: {
    eyebrow: "02 — O ponto de encontro",
    label: "Como os dois apps se encontram na DHT",
    steps: [
      {
        title: "Uma rede pública, sem dono.",
        body: "Para se acharem, os dois apps usam a DHT Mainline — milhões de computadores que já ajudam usuários de BitTorrent a se encontrar — por meio do Pkarr. Não há um servidor do Ghostly no meio.",
        note: "Navegadores chegam à DHT por relays públicos do Pkarr; o app desktop e a CLI também falam com ela diretamente.",
      },
      {
        title: "Bilhetes pequenos, assinados e selados.",
        body: "O Boo deixa alguns registros minúsculos em lugares diferentes da rede. Cada um é assinado, e o que importa lá dentro é criptografado. São bilhetes, não uma caixa postal: menos de um kilobyte cada.",
      },
      {
        title: "Só o convite abre.",
        body: "O Casper sabe onde procurar e como ler, porque o convite diz. Quem passar por ali vê registros selados que não consegue interpretar.",
      },
      {
        title: "Depois, eles somem.",
        body: "Os registros são republicados enquanto você está online. Quando você para, ninguém os renova: eles envelhecem para fora da rede e os apps deixam de aceitar os antigos. Isso não apaga cópias que alguém já tenha feito, nem o histórico no seu aparelho.",
      },
    ],
    tags: { sealed: "selado", ttl: "expira" },
  },
  agree: {
    eyebrow: "03 — O acordo",
    label: "Como os dois lados combinam o que usar",
    steps: [
      {
        title: "Cada lado diz o que sabe fazer.",
        body: "O app desktop do Boo e o navegador do Casper listam as capacidades que suportam, com versões, e os caminhos que preferem.",
      },
      {
        title: "Fica o que os dois têm.",
        body: "Não é sorteio nem mágica: só o que aparece nas duas listas é usado. O que falta de um lado simplesmente fica desligado.",
      },
      {
        title: "Um plano que os dois aceitaram.",
        body: "Chat, arquivos e Cashu, por WebRTC — porque é isso que esses dois têm em comum. Troque os apps, e o plano muda junto.",
        note: "Capacidades negociadas chegam com os chats pareados, na próxima versão. Os chats da versão atual usam um conjunto fixo.",
      },
    ],
    boo: "Boo · desktop",
    casper: "Casper · navegador",
    plan: "O plano",
  },
  alive: {
    eyebrow: "04 — A conexão ganha vida",
    label: "Como a conversa sai da DHT para uma conexão direta",
    steps: [
      {
        title: "A DHT só fez as apresentações.",
        body: "Os registros de encontro são pequenos de propósito. Quando Boo e Casper sabem como se alcançar, a conversa sai deles.",
      },
      {
        title: "Uma linha direta para a conversa de verdade.",
        body: "Mensagens, arquivos e pagamentos vão por uma conexão ao vivo entre os dois aparelhos: WebRTC no app web, na extensão e no desktop, e Iroh ou HyperDHT entre apps desktop na próxima versão. Chamadas usam mídia WebRTC.",
      },
      {
        title: "Sincero sobre o caminho.",
        body: "Servidores STUN públicos ajudam os aparelhos a achar uma rota através dos roteadores de casa. Se não houver caminho direto, a conexão pode falhar — dá para adicionar seu próprio relay TURN nos ajustes.",
        note: "Textos bem curtos ainda podem viajar como registros na DHT quando não há link ao vivo — até 500 bytes hoje, 256 bytes nos chats pareados.",
      },
    ],
    pipe: "conexão ao vivo",
    thread: "encontro",
  },
  next: {
    eyebrow: "05 — E depois",
    title: "Agora que vocês estão conectados.",
    lead: "Tudo aqui está na versão atual, a menos que o selo diga outra coisa.",
    shot: "Captura de tela do app Ghostly",
    illustration: "Ilustração",
    fromDev: "Build de desenvolvimento, {n}",
    fromOld: "Um build anterior",
    items: [
      {
        id: "chat",
        icon: "chat",
        title: "Diga do seu jeito.",
        body: "Conversas privadas um a um, com confirmação de entrega e histórico local. Sem número de telefone, sem perfil público.",
        level: "released",
        extra: "Chats pareados — com chaves fixadas, nomes e fotos — estão em desenvolvimento.",
        extraLevel: "development",
      },
      {
        id: "files",
        icon: "file",
        title: "Mande a coisa em si.",
        body: "Fotos, documentos, projetos: direto do seu aparelho para o da outra pessoa, verificados na chegada.",
        level: "released",
        extra: "Até 100 MiB por arquivo, com os dois online.",
      },
      {
        id: "calls",
        icon: "video",
        title: "Fique mais perto.",
        body: "Voz, vídeo e compartilhamento de tela, um a um.",
        level: "released",
        extra: "Em chats sobre WebRTC. Compartilhar a tela exige um computador. Os chats pareados ainda não têm chamadas.",
      },
      {
        id: "sats",
        icon: "bolt",
        title: "Um agradinho.",
        body: "Envie ou peça sats na própria conversa, como ecash Cashu ou uma fatura Lightning.",
        level: "released",
        extra: "Um mint Cashu que você escolhe guarda os fundos e cuida da Lightning. Escolha um em que você confia.",
      },
      {
        id: "identities",
        icon: "badge",
        title: "Prove quem você é. Só para quem você escolher.",
        body: "Vincule uma identidade externa ao seu perfil uma vez — uma chave Nostr, um domínio, uma chave OpenPGP ou SSH, um endereço Bitcoin — e compartilhe com um contato por vez. O app dele verifica no aparelho.",
        level: "development",
        extra: "Nunca é exigido para conversar. Retire por contato, ou revogue em todo lugar. Contas no Google, Microsoft, Apple, GitLab ou Twitch estão integradas, mas esperam o registro dos clientes.",
      },
      {
        id: "services",
        icon: "window",
        title: "Feito aqui. Aberto lá.",
        body: "Deixe um contato abrir um app web que roda no seu computador — uma galeria de fotos, um painel, um protótipo — enquanto você está online.",
        level: "released",
        extra: "App desktop ou extensão nas duas pontas. Pedidos HTTP simples: sem WebSockets nem streaming. Escolher exatamente quais contatos veem cada app está em desenvolvimento.",
      },
      {
        id: "cli",
        icon: "terminal",
        title: "Dê voz ao seu código.",
        body: "Um cliente de linha de comando para scripts, bots e agentes: criar identidade e convites, enviar, receber e acompanhar um chat como um fluxo JSON.",
        level: "released",
        extra: "Só mensagens de texto. Os convites dela são para outros peers da CLI; conversar com o app exige passar as chaves à mão.",
        link: { label: "Guia da CLI (em inglês)", href: "/cli" },
      },
    ],
  },
  space: {
    eyebrow: "06 — Seu espaço",
    title: "Tudo continua seu, no seu aparelho.",
    lead: "Chats, chaves, carteiras e serviços ficam no app. Nenhum servidor nosso.",
    profiles: {
      title: "Vidas separadas, um aparelho.",
      level: "development",
      note: "Os contatos nunca sabem dos outros · web e desktop; a extensão roda um único perfil",
      names: ["Pessoal", "Trabalho", "Clube"],
    },
    backup: {
      title: "Backup é o quê. Armazenamento é onde.",
      level: "development",
      what: "Backup",
      where: "Armazenamento",
      whatItems: ["chats e chaves", "carteiras", "serviços", "ajustes"],
      whereItems: ["um arquivo seu", "S3 · R2 · B2 · MinIO"],
      note: "Selado com a sua senha · restaurar cria um perfil novo, nada é sobrescrito",
    },
    look: {
      title: "Deixe com a sua cara.",
      level: "released",
      note: "Quatro temas · claro ou escuro · oito idiomas · trava do app",
    },
  },
  wallets: {
    title: "Uma carteira, muitas formas de pagar.",
    lead: "Cada método de pagamento é um cartão, com as próprias regras. Escolha um para ver o que ele faz e o quanto está pronto.",
    hint: "Escolha um cartão",
    testnet: "Uma chave de Testnet leva todas as carteiras para redes de teste de uma vez — em desenvolvimento.",
    cards: [
      {
        id: "cashu",
        name: "Cashu",
        kind: "ecash",
        level: "released",
        body: "Tokens de ecash privados que você pode passar numa conversa. Um mint que você escolhe guarda os fundos.",
        limits: "Confie no mint que escolher: ele vê as próprias operações e guarda os sats que dão lastro.",
      },
      {
        id: "lightning",
        name: "Lightning",
        kind: "faturas",
        level: "released",
        body: "Pague e receba faturas Lightning pelo chat.",
        limits: "Pelo seu mint Cashu na versão atual. Na próxima, seu próprio nó ou carteira pode ser a fonte: NWC, LND, Core Lightning, uma carteira do navegador (WebLN, só no app web) ou Breez num regtest local.",
        more: "development",
      },
      {
        id: "ark",
        name: "Ark",
        kind: "via Arkade",
        level: "development",
        body: "Revise e aprove um pagamento Ark exato por um operador fixado.",
        limits: "Experimental. Perfis novos ganham automaticamente uma carteira Ark na mainnet do Bitcoin, mas os pagamentos foram exercitados só numa rede de teste local; sair do Ark por conta própria ainda é requisito de lançamento.",
      },
      {
        id: "bark",
        name: "Bark",
        kind: "Ark da Second",
        level: "development",
        body: "Um segundo provedor de Ark ao lado do Arkade: a mesma ideia, outro servidor, uma forma própria de pagar.",
        limits: "Experimental, só em redes de teste (o servidor signet da Second ou um regtest local); a Mainnet ainda não cria carteira Bark. Não é intercambiável com o Arkade: uma carteira Bark não paga um endereço Arkade.",
      },
      {
        id: "usdt",
        name: "USDT",
        kind: "Tether WDK",
        level: "development",
        body: "Receba e envie USDT na Ethereum, assinado no seu aparelho.",
        limits: "Experimental. Os pagamentos foram validados numa rede de teste local, não com fundos reais. Só Ethereum; existe um modo de teste na Sepolia.",
      },
      {
        id: "onchain",
        name: "Bitcoin",
        kind: "on-chain",
        level: "development",
        body: "Bitcoin on-chain no chat, por uma carteira BDK ou pelo seu próprio nó Bitcoin Core.",
        limits: "Experimental. BDK só em signet, Mutinynet ou regtest; o Bitcoin Core exige o app desktop. Pagamentos on-chain só são oferecidos dentro de uma sessão pareada aberta.",
      },
    ],
  },
  open: {
    eyebrow: "07 — Por baixo dos fantasmas",
    label: "As peças que formam o Ghostly",
    steps: [
      {
        title: "Tudo o que você acabou de ver…",
        body: "…é um app compondo peças independentes: um núcleo pequeno de encontro, transportes e capacidades como chat, arquivos e pagamentos.",
      },
      {
        title: "…é feito de peças abertas.",
        body: "Cada peça é descrita num WISP, um contrato público em rascunho. Outro app pode implementar só as peças de que precisa e ainda assim encontrar o Ghostly no meio do caminho.",
      },
    ],
    layers: ["Ghost · encontro e chaves", "Transportes", "Chat · arquivos · chamadas", "Pagamentos · serviços", "Provas de identidade · opcional", "Perfis · backup · armazenamento", "O seu app"],
    cta: "Construa com o Ghostly",
    catalog: "Ver os WISPs",
  },
  finale: {
    eyebrow: "08 — Sua vez",
    title1: "Um passinho.",
    title2: "Você já é um fantasma.",
    lead: "Abra o Ghostly no navegador e convide alguém que você conhece. Ou leve com você no desktop.",
    browser: {
      title: "No navegador",
      body: "Nada para instalar. Abra uma aba e crie um convite.",
      cta: "Abrir app.ghostly.tools",
    },
    desktop: {
      title: "Para o seu computador",
      body: "O app de desktop para macOS, Windows e Linux — o mesmo Ghostly, instalado.",
      platforms: {
        mac: { name: "macOS", chip: "Para este Mac" },
        windows: { name: "Windows", chip: "Para este PC" },
        linux: { name: "Linux", chip: "Para esta máquina" },
      },
      installers: {
        macArm: "Apple silicon",
        macIntel: "Intel",
        windowsExe: "Instalador",
        windowsMsi: "Pacote",
        linuxDeb: "Debian / Ubuntu",
        linuxAppImage: "Qualquer distro",
      },
    },
    extension: {
      title: "Extensão do navegador",
      body: "Chrome e navegadores Chromium, como .zip para carregar sem empacotar.",
      cta: "Baixar",
    },
    cli: { title: "Linha de comando", body: "Para scripts, bots e agentes.", cta: "Guia da CLI (em inglês)" },
    note: "Os downloads são a versão pública, v{v}. Recursos marcados “em desenvolvimento” chegam com a {n}.",
    all: "Todos os arquivos da versão",
    conversation: [
      { side: "boo", text: "Buu! 👻" },
      { side: "casper", text: "Achei você." },
      { side: "boo", text: "Quer ver meu app?" },
      { side: "casper", text: "Ele tá no seu localhost…" },
      { side: "boo", text: "Não mais ✨" },
      { side: "casper", text: "Toma, 21 sats ⚡" },
      { side: "boo", text: "Até mais." },
      { side: "casper", text: "*puf* 👻" },
    ],
  },
};

export const home: Localized<HomeCopy> = { en, "pt-br": ptBr };
