
export const reader = {
  developers: "Developers",
  catalog: "WISP catalog",
  reference: "Reference",
  inShort: "In short",
  implementation: "Implementation, as the document states it",
  inApp: "In the app",
  depends: "Builds on",
  usedBy: "Used by",
  children: "Adapters and profiles",
  implementsContract: "Implements",
  contents: "On this page",
  all: "All drafts",
  expandAll: "Expand all",
  collapseAll: "Collapse all",
  glossary: "Glossary",
  moved: "This draft has a new number. You're reading it at its current address; the old link keeps working.",
  draftNote: "A review draft, not a final standard, and not a promise that every client supports it.",
  supportNote: "Supporting documentation. It can include dated proposals and historical evidence.",
  source: "View source on GitHub",
  download: "Download Markdown",
  prev: "Previous",
  next: "Next",
  back: "Back to the catalog",
  updated: "Updated",
  unassigned: "Planned · number to be defined",
  video: "Video lesson",
  chapters: "Chapters",
  repo: "repository",
};

export type ReaderCopy = typeof reader;
