import numbering from "./wisp-numbering.json";
export type Family =
  | "Core"
  | "Connections"
  | "Identity"
  | "Experiences"
  | "Payments"
  | "Groups"
  | "Storage";
export type Wisp = {
  number: string;
  kind: string;
  displayNumber: string;
  numberAssignment: string;
  title: string;
  family: Family;
  file: string;
  purpose: string;
  availability: string;
  evidence: string;
  state: "Implemented, scoped" | "Deferred" | "Proposal" | "In development";
};
const rows: [
  string,
  string,
  Family,
  string,
  string,
  string,
  string,
  Wisp["state"],
][] = [
  [
    "01",
    "Process",
    "Core",
    "process",
    "Make contracts reviewable, versioned and independently testable.",
    "Contributor process proposal.",
    "No acceptance or Final status claimed.",
    "Proposal",
  ],
  [
    "02",
    "Ghost Core",
    "Core",
    "ghost-core",
    "Find a peer through small signed records, without turning discovery into a general storage service.",
    "Current Pkarr rendezvous; native DHT and browser relay paths differ.",
    "Existing implementation; modular contract under review.",
    "Implemented, scoped",
  ],
  [
    "03",
    "Peer Keys",
    "Core",
    "peer-keys",
    "Keep participation tied to a connection, with explicit peer authentication.",
    "Current per-link keys, pins and comparison codes.",
    "Local authentication and persistence checks; lifecycle extensions proposed.",
    "Implemented, scoped",
  ],
  [
    "04",
    "Capabilities",
    "Core",
    "capabilities",
    "Agree on the versioned abilities both peers can use.",
    "Current paired offers admit chat, files and payments only when supported.",
    "Local compatibility and negative-admission tests; broader draft remains a proposal.",
    "Implemented, scoped",
  ],
  [
    "— 04",
    "Local Profiles",
    "Core",
    "profiles",
    "Keep separate lives on one device: chats, wallets, services and settings grouped per profile, never announced to contacts.",
    "Web and desktop clients: create with an automatic color, rename, recolor and switch by restart. The extension runs one profile.",
    "Unit tests for the registry, isolation and profile-scoped clearing; a browser end-to-end switch test. Removal and export remain open.",
    "In development",
  ],
  [
    "— 05",
    "Profile Backups",
    "Core",
    "backups",
    "Bring a whole profile back — chats, keys, wallets, services and settings — from one encrypted bundle.",
    "Web and desktop: passphrase-sealed, compressed bundles; restore always creates a new profile and moves Ark databases to fresh ids.",
    "Unit round trip of every store, blobs and wallet relocation; end-to-end backup to a local S3 server and to a file.",
    "In development",
  ],
  [
    "05",
    "Transport Negotiation",
    "Connections",
    "transports",
    "Choose a shared data path while keeping preference separate from the actual connection.",
    "Current paired profile; fallback requires agreement.",
    "Local negotiation and reconnect tests, not seamless stream migration.",
    "Implemented, scoped",
  ],
  [
    "06",
    "WebRTC",
    "Connections",
    "webrtc",
    "Carry a session over a supported WebRTC data channel.",
    "Browser and extension; native WebView support varies. Initial product pairing uses WebRTC.",
    "Local browser integration; media has its own profile limits.",
    "Implemented, scoped",
  ],
  [
    "07",
    "Iroh",
    "Connections",
    "iroh",
    "Use an Iroh endpoint with Ghostly authentication bound to its connection.",
    "Native paired adapter; tested local macOS arm64 bundle.",
    "Real local QUIC tests; shared core is not an independent implementation.",
    "Implemented, scoped",
  ],
  [
    "08",
    "HyperDHT",
    "Connections",
    "hyperdht",
    "Use an authenticated Noise stream discovered through HyperDHT.",
    "Native bundled runtime; not advertised by the browser client.",
    "Local native stream/reconnect tests; release platforms need separate validation.",
    "Implemented, scoped",
  ],
  [
    "09",
    "Identity Proofs",
    "Identity",
    "peer-proofs",
    "Optionally link a participation key to an external proof, without requiring a public identity.",
    "External proofs disabled in the current Ghostly-only scope.",
    "Prior experiments are preserved; not a release feature.",
    "Deferred",
  ],
  [
    "10",
    "Nostr",
    "Identity",
    "nostr",
    "Describe an optional Nostr proof and its signer boundaries.",
    "Deferred together with external profiles and proofs.",
    "Historical experimental subset; no current enabled integration.",
    "Deferred",
  ],
  [
    "11",
    "Pubky",
    "Identity",
    "pubky",
    "Explore a supported Pubky identity binding.",
    "Deferred; standard auth does not imply arbitrary signing.",
    "Storage-proof work unfinished; independent validation and cleanup required.",
    "Deferred",
  ],
  [
    "12",
    "Keet",
    "Identity",
    "keet",
    "Explore an optional identity relationship with Keet.",
    "Deferred; an existing-account app bridge is not available.",
    "Compatible key import experiments do not establish a supported Keet API.",
    "Deferred",
  ],
  [
    "13",
    "Chat Messaging",
    "Experiences",
    "chat",
    "Exchange messages with explicit receipt and retry semantics.",
    "Current paired and legacy 1:1 profiles; bounded DHT text is a separate path.",
    "Local persistence, receipt and deduplication tests; no global exactly-once claim.",
    "Implemented, scoped",
  ],
  [
    "14",
    "File Transfer",
    "Experiences",
    "files",
    "Transfer bounded files and acknowledge verified local storage.",
    "Paired files/2 and legacy transfer. Up to 100 MiB, both peers online.",
    "Chunk integrity, storage failure and replay tests. Retry starts the full file.",
    "Implemented, scoped",
  ],
  [
    "15",
    "Voice & Video",
    "Experiences",
    "media",
    "Coordinate real-time media separately from a generic byte stream.",
    "Compatible legacy WebRTC chats; not current paired sessions.",
    "Existing 1:1 behavior; platform permissions and WebView support vary.",
    "Implemented, scoped",
  ],
  [
    "16",
    "Local Services",
    "Experiences",
    "local-services",
    "Make a local HTTP service reachable through a permitted connection.",
    "Legacy desktop/extension sharing; not current paired hosted HTTP.",
    "Existing proxy behavior; a transport adapter alone does not add service support.",
    "Implemented, scoped",
  ],
  [
    "17",
    "Payment Negotiation",
    "Payments",
    "payments",
    "Agree on a payment intent and supported method, separately from authorization to spend.",
    "Current paired payments/1 plus existing legacy frames; generalized methods proposed.",
    "Admission, receipt and replay tests. Native fixtures are not real mint settlement.",
    "Implemented, scoped",
  ],
  [
    "18",
    "Cashu",
    "Payments",
    "cashu",
    "Send and receive sats through the existing ecash wallet.",
    "Current application integration; accepted-mint and wallet rules apply.",
    "Local disposable-mint tests; mints hold funds and crash recovery has limits.",
    "Implemented, scoped",
  ],
  [
    "19",
    "Lightning",
    "Payments",
    "lightning",
    "Connect payment requests to Lightning invoice flows.",
    "Current invoice integration through the Cashu wallet; not arbitrary node support.",
    "Existing wallet regression tests; NWC, LND and Core Lightning remain candidates.",
    "Implemented, scoped",
  ],
  [
    "20",
    "Invite & Join",
    "Groups",
    "invite-join",
    "Separate a private invitation from admission to a future group.",
    "Bearer invites exist; expanded admission semantics are proposed.",
    "Current invite UX does not implement group authorization.",
    "Proposal",
  ],
  [
    "21",
    "Group Sessions",
    "Groups",
    "group-sessions",
    "Agree on membership, roles, epochs and a shared group profile.",
    "Proposed; no current group implementation.",
    "Requires membership, removal, partition and recovery evidence.",
    "Proposal",
  ],
  [
    "22",
    "GossipSub",
    "Groups",
    "gossipsub",
    "Offer a group distribution adapter without dictating every group’s transport.",
    "Proposed optional profile; no Ghostly adapter implemented.",
    "Requires group authentication, abuse bounds and interoperability tests.",
    "Proposal",
  ],
  [
    "— 1000",
    "Storage Contract",
    "Storage",
    "storage",
    "Keep encrypted bundles in places people choose, behind one contract every adapter implements.",
    "Object contract, non-identifying names and adapter rules; used by profile backups.",
    "Exercised through the local file and S3-compatible adapters.",
    "In development",
  ],
  [
    "— 1001",
    "Local File Storage",
    "Storage",
    "local-storage",
    "A backup as a file the person keeps: no account, network or credential.",
    "Download and pick-a-file restore in web and desktop.",
    "End-to-end download and restore.",
    "In development",
  ],
  [
    "— 1002",
    "S3-Compatible Storage",
    "Storage",
    "s3-storage",
    "Backups in any S3-compatible bucket, signed in the client with SigV4.",
    "AWS, R2, Backblaze, MinIO and others; bucket CORS required for browser clients.",
    "SigV4 checked against AWS's published example; end-to-end against a local S3 server.",
    "In development",
  ],
];
rows.push(...([
  ["202", "Ark via Arkade", "Payments", "arkade", "Review and approve an exact Ark payment through a pinned operator.", "Experimental test-network adapter; regtest transfer and HD return payment verified. Mainnet disabled.", "Real local regtest, provider-signature checks and shared coordinator tests; encrypted backup restore verified; exit UI remains a release gate.", "In development"],
  [
    "401",
    "Paired Chat",
    "Experiences",
    "paired-chat",
    "Authenticated chat/1 over negotiated live data links.",
    "Current paired WebRTC; native Iroh/HyperDHT where supported.",
    "Local persistence, authenticated receipt and replay tests; no independent implementation claim.",
    "Implemented, scoped"
  ],
  [
    "402",
    "Legacy Timestamp Chat",
    "Experiences",
    "legacy-chat",
    "Document the existing timestamp message frames and encrypted record batches.",
    "Existing legacy 1:1 clients.",
    "Current frame/record implementation; timestamp collisions and best-effort delivery remain limits.",
    "Implemented, scoped"
  ],
  [
    "403",
    "Bounded DHT Text",
    "Experiences",
    "dht-text",
    "Deliver short authenticated text using separate directional Pkarr mailboxes.",
    "Modern DHT-only and explicitly permitted fallback paths; native DHT versus browser relays differ.",
    "Local persistence/replay/size tests; relay success does not prove public UDP propagation.",
    "Implemented, scoped"
  ],
  [
    "501",
    "Paired Files",
    "Experiences",
    "paired-files",
    "Map files/2 to bounded authenticated frames and final storage receipts.",
    "Negotiated paired data links; WebRTC and supported native adapters.",
    "Digest, storage failure, duplicate and disconnect checks; retry restarts the file.",
    "Implemented, scoped"
  ],
  [
    "502",
    "Legacy File Frames",
    "Experiences",
    "legacy-files",
    "Map existing file announcements and binary chunks to legacy 1:1 transfer.",
    "Legacy live data links; both peers online.",
    "Existing FileTransfers tests; no paired digest/storage receipt promise.",
    "Implemented, scoped"
  ],
  [
    "601",
    "WebRTC Media",
    "Experiences",
    "webrtc-media",
    "Bind legacy 1:1 call signaling to WebRTC voice, camera and screen tracks.",
    "Compatible legacy WebRTC chats; capture varies by platform; not current paired sessions.",
    "Existing call validation/hooks; no group calls or arbitrary transport media claim.",
    "Implemented, scoped"
  ],
  [
    "701",
    "HTTP Local Service Profile",
    "Experiences",
    "http-services",
    "Map permitted loopback services to ghostly-http/1 requests and responses.",
    "Legacy desktop/extension hosting; web viewer where supported; not paired hosted HTTP.",
    "Current proxy/path/header/redirect bounds and explicit per-contact sharing controls.",
    "Implemented, scoped"
  ],
  [
    "801",
    "Implemented Invitation Profiles",
    "Groups",
    "invitation-profiles",
    "Describe existing bearer invitation formats and modern participation bootstrap.",
    "Current modern pair1/pair2d creation plus legacy imports.",
    "Existing invitation parsers and TOFU pairing; no globally consumable invite guarantee.",
    "Implemented, scoped"
  ]
] satisfies typeof rows));
export const wisps: Wisp[] = rows.map(
  ([number, title, family, , purpose, availability, evidence, state]) => ({
    number: numbering.find((entry) => entry.oldId === number)!.id,
    kind: numbering.find((entry) => entry.oldId === number)!.kind,
    displayNumber: numbering.find((entry) => entry.oldId === number)!.displayNumber,
    numberAssignment: numbering.find((entry) => entry.oldId === number)!.numberAssignment,
    title,
    family,
    file: numbering.find((entry) => entry.oldId === number)!.file,
    purpose,
    availability,
    evidence,
    state,
  }),
).sort((a, b) => Number(a.number) - Number(b.number));
export const families: Family[] = [
  "Core",
  "Connections",
  "Identity",
  "Experiences",
  "Payments",
  "Groups",
  "Storage",
];
