import 'fake-indexeddb/auto';
import { test,expect,vi } from 'vitest';
import { Wallet } from '@cashu/cashu-ts';
import { CashuWallet } from '../src/engine/wallet';
import { CashuAdapter } from '../src/engine/paymentAdapters/cashu';
import { PaymentCoordinator } from '../src/engine/paymentAdapters/coordinator';
import { intentRepository } from '../src/engine/paymentAdapters/persistence';
import { STORES,transact } from '../src/shared/idb';
import { TEST_MINT } from '../src/shared/mints';
// covers-gated: payments.cashu.send, payments.chat.review, payments.chat.reconcile

test.skipIf(process.env.GHOSTLY_CASHU_TEST!=='1')('disposable test-mint funds use reviewed Cashu adapter and mint-confirmed redemption',async()=>{
 const faucet=new Wallet(TEST_MINT,{unit:'sat'});await faucet.loadMint();
 const quote=await faucet.createMintQuoteBolt11(128);
 await expect.poll(async()=>(await faucet.checkMintQuoteBolt11(quote.quote)).state,{timeout:60000,interval:1000}).toBe('PAID');
 const proofs=await faucet.mintProofsBolt11(128,quote.quote);
 await transact([STORES.proofs],stores=>{for(const p of proofs)stores[STORES.proofs].put({...p,amount:p.amount.toNumber(),mint:TEST_MINT});});
 const wallet=new CashuWallet(()=>[TEST_MINT],{onChange(){},async onTestMintNeeded(){},onQuotePaid(){},onMeltResolved(){}});
 let sent='';
 const adapter=new CashuAdapter(wallet,async(_review,token)=>{sent=token;});
 const coordinator=new PaymentCoordinator(intentRepository,[adapter]);
 const review=await coordinator.prepare({method:'cashu',network:'cashu-test',provider:TEST_MINT,address:'disposable request',asset:'BTC',unit:'sat',expiresAt:Date.now()+60000},32,10,{payee:'disposable recipient',linkId:'disposable link',requestId:crypto.randomUUID()});
 expect(sent).toBe('');
 await expect(coordinator.prepare(review,32,review.fee-1,{payee:'disposable recipient',linkId:'disposable link',requestId:crypto.randomUUID()})).rejects.toThrow('fee exceeds');
 expect((await wallet.view()).mints.find(m=>m.url===TEST_MINT)?.balance).toBe(128);
 expect((await coordinator.approve(review.id)).state).toBe('submitted');
 expect((await wallet.view()).mints.find(m=>m.url===TEST_MINT)?.balance).toBe(128-review.amount-review.fee);
 expect(sent).toMatch(/^cashu/);
 const receiver=new Wallet(TEST_MINT,{unit:'sat'});await receiver.loadMint();
 const received=await receiver.receive(sent);
 expect(received.reduce((n,p)=>n+p.amount.toNumber(),0)).toBe(32);
 expect((await coordinator.reconcile(review.id)).state).toBe('settled');
 await expect(coordinator.approve(review.id)).rejects.toThrow('cannot be submitted');
 // The mint swaps successfully but its HTTP response is lost before local booking.
 const sdk=await wallet['wallet'](TEST_MINT);
 const complete=sdk.completeSwap.bind(sdk);
 const swap=vi.spyOn(sdk,'completeSwap').mockImplementationOnce(async(preview)=>{await complete(preview);throw new Error('simulated lost response');});
 const second=await coordinator.prepare({...review,address:'second disposable request',expiresAt:Date.now()+60000},16,10,{payee:'disposable recipient',linkId:'disposable link',requestId:crypto.randomUUID()});
 expect((await coordinator.approve(second.id)).state).toBe('unknown');
 sent='';
 const restarted=new PaymentCoordinator(intentRepository,[adapter]);
 expect((await restarted.reconcile(second.id)).state).toBe('unknown');
 expect(sent).toMatch(/^cashu/);
 const restored=await receiver.receive(sent);
 expect(restored.reduce((n,p)=>n+p.amount.toNumber(),0)).toBe(16);
 expect((await restarted.reconcile(second.id)).state).toBe('settled');
 expect(swap).toHaveBeenCalledTimes(1);
 expect((await wallet.view()).mints.find(m=>m.url===TEST_MINT)?.balance).toBe(128-review.amount-review.fee-second.amount-second.fee);
 swap.mockRestore();
},90000);
