import "fake-indexeddb/auto";
import { createHash } from "node:crypto";
import { afterEach, expect, it, vi } from "vitest";
import { ChatFiles, FILE_LIMITS, GhostLink, createIdentity, createLink, identityFromSeedB64, type FileTransferRecord, type IncomingTarget, type OfferDecision } from "@ghostly/core";
import { GhostlyNode } from "../src/engine/node";
import { db } from "../src/engine/db";
import { fileStore } from "../src/shared/idb";
import { fileBytes, registerFileBytes } from "../src/shared/fileBytes";
import { IdbFileBytes } from "../src/shared/fileBytesIdb";
import { FakeNativeNet } from "./helpers/fakeNative";
// covers: files.large.offer, files.large.resume, files.large.integrity, files.storage, files.large.resend, files.large.request

/**
 * files/3 in the engine: a real node (the app) and its contact's link over stand-ins for Iroh and HyperDHT, the
 * contact speaking files/3 with a bare `ChatFiles`. What the app receives lands in file storage (IndexedDB pieces
 * here), a large file waits for the person, and a drop or a restart of the app resumes where it stopped.
 */

function pattern(offset: number, length: number): Uint8Array {
  const out = new Uint8Array(length);
  for (let i = 0; i < length; i++) out[i] = ((offset + i) * 7 + ((offset + i) >>> 13)) & 0xff;
  return out;
}
function digestOf(size: number): string {
  const hash = createHash("sha256");
  for (let offset = 0; offset < size; offset += 1 << 20) hash.update(pattern(offset, Math.min(1 << 20, size - offset)));
  return hash.digest("base64url");
}

// Node has no storage estimate: this device says it has 40 GiB left for files.
Object.defineProperty(globalThis.navigator, "storage", { value: { estimate: async () => ({ quota: 50 * 1024 ** 3, usage: 10 * 1024 ** 3 }) }, configurable: true });

const cleanup: (() => Promise<void>)[] = [];
afterEach(async () => { for (const step of cleanup.splice(0).reverse()) await step(); });

async function setup() {
  const net = new FakeNativeNet();
  // As the real Iroh and HyperDHT channels: past 120 KiB queued, a frame is refused.
  net.sendBudget = 120 * 1024;
  const invitation = createLink();
  const [mine, theirs] = [createIdentity().seedB64, createIdentity().seedB64];
  const id = `files3-${crypto.randomUUID()}`;
  await db.putSettings({ online: true, nick: "", relays: [], iceServers: [], mints: [], mintsInitialized: true });
  await db.putLink({ ...invitation.mine, id, profile: "paired-chat/1", participationSeed: mine, createdAt: 1,
    pairedPeerKey: identityFromSeedB64(theirs).pubKeyZ32,
    peerTransports: ["iroh/1", "hyperdht/1"], peerFallback: true, preferredTransport: "iroh/1", transportFallback: true,
    peerDescriptors: { "iroh/1": { id: "contact:iroh/1" }, "hyperdht/1": { id: "contact:hyperdht/1" } } });
  const transport = { publish: vi.fn(async () => {}), resolve: vi.fn(async () => null), describe: () => ({ protocol: "in-process", relays: [] }) };
  const makeNode = () => new GhostlyNode({ onState: vi.fn(), onMessages: vi.fn(), onCallSignal: vi.fn() }, { transport, automaticWallets: false,
    nativeTransports: { "iroh/1": async () => net.endpoint("iroh/1", "app"), "hyperdht/1": async () => net.endpoint("hyperdht/1", "app") } });

  // The contact: its own ChatFiles, sending generated bytes and keeping a hash of what it receives.
  const received = new Map<string, { hash: ReturnType<typeof createHash>; length: number }>();
  const records = new Map<string, FileTransferRecord>();
  const sources = new Map<string, { size: number; digest?: string }>();
  let decide: (size: number) => OfferDecision = () => "accept";
  const peer: { link?: GhostLink } = {};
  const files = new ChatFiles({
    send: (frame) => peer.link?.sendFilesFrame(frame) ?? false,
    decide: async (file) => decide(file.size),
    openTarget: async (record): Promise<IncomingTarget> => {
      const disk = received.get(record.id) ?? { hash: createHash("sha256"), length: 0 };
      received.set(record.id, disk);
      return { offset: disk.length, append: async (bytes) => { disk.hash.update(bytes); disk.length += bytes.length; }, flush: async () => {},
        verify: async (digest) => disk.hash.copy().digest("base64url") === digest, discard: async () => { received.delete(record.id); } };
    },
    openSource: async (record) => {
      const { size, digest } = sources.get(record.id)!;
      return { read: async (offset, length) => pattern(offset, Math.min(length, size - offset)), digest: async () => digest ?? digestOf(size) };
    },
    changed: (record) => { records.set(`${record.direction}:${record.id}`, record); },
    room: async () => 50 * 1024 ** 3,
    writable: () => peer.link?.filesWritable(),
  });
  const contact = new GhostLink({
    params: { ...invitation.invite, profile: "paired-chat/1" }, rtcAvailable: false, largeFilesSupport: true,
    pairing: { credentials: { seedB64: theirs, peerKey: identityFromSeedB64(mine).pubKeyZ32 }, pinPeer: async () => {} },
    native: { preferred: "iroh/1", fallback: true, peerTransports: ["iroh/1", "hyperdht/1"], peerFallback: true,
      peerDescriptors: { "iroh/1": { id: "app:iroh/1" }, "hyperdht/1": { id: "app:hyperdht/1" } } },
    transport, createPeerConnection: () => { throw new Error("No WebRTC here"); }, localFetch: vi.fn(), getServices: () => [], getHostedHttpService: () => undefined,
    events: { onFilesFrame: (frame) => files.handle(frame), onFilesSession: (open) => { if (open) files.attach(); else files.detach(); } },
  });
  peer.link = contact;
  contact.registerEndpoint(net.endpoint("iroh/1", "contact"));
  contact.registerEndpoint(net.endpoint("hyperdht/1", "contact"));
  let node = makeNode();
  cleanup.push(async () => { await contact.stop(false); await node.shutdown(); await db.deleteLink(id); });
  const open = async () => {
    await node.start();
    node.setActiveLink({ linkId: id });
    await vi.waitFor(() => expect(node.getState().links.find(l => l.id === id)?.availableTransports).toHaveLength(2));
    void contact.connect(5_000).catch(() => {});
    await vi.waitFor(() => expect(node.getState().links.find(l => l.id === id)?.capabilities?.largeFiles).toBe(true), { timeout: 10_000 });
    await vi.waitFor(() => expect(files.live).toBe(true));
  };
  await open();
  const offer = (wireId: string, size: number, digest?: string) => {
    sources.set(wireId, { size, digest });
    files.offer({ id: wireId, name: `${wireId}.bin`, mime: "application/octet-stream", size, timestamp: Date.now() });
  };
  /** The local id and transfer of a file the contact sent, by its wire id. */
  const incoming = async (wireId: string) => {
    const message = (await db.getMessages(id)).find((m) => m.id === `peer_${wireId}`);
    return message?.file ? { fileId: message.file.id, transfer: node.getState().transfers[message.file.id] } : null;
  };
  return {
    net, id, files, records, received, contact, offer, incoming,
    node: () => node,
    set decide(fn: (size: number) => OfferDecision) { decide = fn; },
    /** The app quits and starts again, the contact dialling it once it is back. */
    async restartApp() { await node.shutdown(); node = makeNode(); await open(); },
    async dropContact() { contact.disconnect(); await vi.waitFor(() => expect(files.live).toBe(false)); void contact.connect(5_000).catch(() => {}); },
  };
}

it("a large file waits for the person, shows the room here, and is stored whole once accepted", async () => {
  const t = await setup();
  const size = FILE_LIMITS.askAboveBytes + 1234;
  t.offer("big-00001", size);
  await vi.waitFor(async () => expect((await t.incoming("big-00001"))?.transfer).toMatchObject({ state: "transferring", stage: "asking", direction: "in" }));
  await vi.waitFor(() => expect(t.records.get("out:big-00001")).toMatchObject({ state: "asking", waitingFor: "consent" }));
  const { fileId } = (await t.incoming("big-00001"))!;
  await vi.waitFor(() => expect(t.node().getState().transfers[fileId].room).toBeTypeOf("number"));
  t.node().fileAction({ linkId: t.id, fileId, action: "accept" });
  await vi.waitFor(() => expect(t.node().getState().transfers[fileId]).toMatchObject({ state: "done", transferred: size }), { timeout: 60_000 });
  await vi.waitFor(() => expect(t.records.get("out:big-00001")?.state).toBe("done"));
  await vi.waitFor(async () => expect((await fileStore.get(fileId))?.wire3?.state).toBe("done"));
  const stored = (await fileStore.get(fileId))!;
  expect(stored).toMatchObject({ direction: "in", wireId: "big-00001", bytes: "idb", wire3: { state: "done", consented: true } });
  expect(stored.blob).toBeUndefined();
  expect(await (await fileBytes()).digest(fileId)).toBe(digestOf(size));
}, 90_000);

it.each([
  { storage: "files on disk (Desktop, web, extension, CLI)", onDisk: true },
  { storage: "IndexedDB pieces", onDisk: false },
])("a file of no bytes arrives, kept as $storage", async ({ onDisk }) => {
  // Found with two headless CLIs: an empty file ended "arrived damaged and was deleted" on both sides. Nothing is
  // ever appended for it, and every backend but IndexedDB reads a file never written as missing: its check failed.
  class FilesOnDisk extends IdbFileBytes {
    private made = new Set<string>();
    override async append(id: string, offset: number, bytes: Uint8Array) { this.made.add(id); await super.append(id, offset, bytes); }
    override async size(id: string) { return this.made.has(id) ? (await super.size(id)) ?? 0 : super.size(id); }
    override async digest(id: string) { if (!this.made.has(id) && (await super.size(id)) === null) throw new Error("No such file"); return super.digest(id); }
  }
  if (onDisk) {
    registerFileBytes("idb", async () => new FilesOnDisk());
    cleanup.push(async () => registerFileBytes("idb", async () => new IdbFileBytes()));
  }
  const t = await setup();
  t.offer("empty-0001", 0);
  await vi.waitFor(async () => expect((await t.incoming("empty-0001"))?.transfer).toMatchObject({ state: "done", transferred: 0 }));
  await vi.waitFor(() => expect(t.records.get("out:empty-0001")?.state).toBe("done"));
  const fileId = (await t.incoming("empty-0001"))!.fileId;
  if (onDisk) expect(await (await fileBytes()).size(fileId)).toBe(0);
  expect((await (await fileBytes()).read(fileId, 0, 16)).length).toBe(0);
}, 60_000);

it("a file under the id of a message the contact sent already is refused, nothing stored for it", async () => {
  const t = await setup();
  const id = "sameidsameidsameidsame";
  expect(await t.contact.sendMessage("hello", Date.now(), id)).toBeNull();
  await vi.waitFor(async () => expect((await db.getMessages(t.id)).some((m) => m.id === `peer_${id}`)).toBe(true));
  t.offer(id, 200_000);
  await vi.waitFor(() => expect(t.records.get(`out:${id}`)?.state).toBe("failed"));
  expect((await db.getMessages(t.id)).filter((m) => m.id === `peer_${id}`).map((m) => m.text)).toEqual(["hello"]);
  expect((await fileStore.listForLink(t.id)).some((f) => f.wireId === id)).toBe(false);
}, 60_000);

it("a small file is taken without asking; a declined one says so to the sender", async () => {
  const t = await setup();
  t.offer("small-0001", 200_000);
  await vi.waitFor(async () => expect((await t.incoming("small-0001"))?.transfer).toMatchObject({ state: "done" }));
  t.offer("nope-00001", FILE_LIMITS.askAboveBytes + 1);
  await vi.waitFor(async () => expect((await t.incoming("nope-00001"))?.transfer?.stage).toBe("asking"));
  t.node().fileAction({ linkId: t.id, fileId: (await t.incoming("nope-00001"))!.fileId, action: "decline" });
  await vi.waitFor(() => expect(t.records.get("out:nope-00001")).toMatchObject({ state: "declined", error: "Declined by your contact" }));
  expect((await t.incoming("nope-00001"))!.transfer).toMatchObject({ state: "failed", error: "You declined it" });
}, 60_000);

it("a drop, then a restart of the app, and the file still arrives whole, from where it stood each time", async () => {
  const t = await setup();
  const size = 24 * 1024 * 1024;
  t.offer("resume-001", size);
  const progress = async () => (await t.incoming("resume-001"))?.transfer?.transferred ?? 0;
  const accepts: number[] = [];
  const handle = t.files.handle.bind(t.files);
  t.files.handle = async (frame) => { if (frame.t === "pf-accept") accepts.push(frame.offset as number); return handle(frame); };
  await vi.waitFor(async () => expect(await progress()).toBeGreaterThan(FILE_LIMITS.checkpointBytes + 1024 * 1024), { timeout: 60_000 });
  accepts.length = 0;
  await t.dropContact();
  await vi.waitFor(async () => expect((await t.incoming("resume-001"))?.transfer?.stage).toBe("waiting"));
  await vi.waitFor(() => expect(t.files.live).toBe(true), { timeout: 20_000 });
  await vi.waitFor(async () => expect(await progress()).toBeGreaterThan(2 * FILE_LIMITS.checkpointBytes + 1024 * 1024), { timeout: 60_000 });
  expect(accepts[0], "after the drop it went on, not from zero").toBeGreaterThan(FILE_LIMITS.checkpointBytes);
  await t.restartApp();
  await vi.waitFor(async () => expect((await t.incoming("resume-001"))?.transfer).toMatchObject({ state: "done", transferred: size }), { timeout: 60_000 });
  expect(accepts.at(-1), "after the restart: its last durable point").toBeGreaterThanOrEqual(2 * FILE_LIMITS.checkpointBytes);
  expect(await (await fileBytes()).digest((await t.incoming("resume-001"))!.fileId)).toBe(digestOf(size));
}, 150_000);

/** A file the app sends, stored as the composer stores it, then sent. */
async function put(t: Awaited<ReturnType<typeof setup>>, wireId: string, size: number, timestamp = 5) {
  const file = { id: `${t.id}-out-${wireId}`, name: `${wireId}.bin`, size, mime: "application/octet-stream" };
  await fileStore.put({ id: file.id, linkId: t.id, blob: new Blob([pattern(0, size) as BlobPart]), createdAt: 1, direction: "out", wireId,
    metadata: { name: file.name, size, mime: file.mime, timestamp } });
  t.node().sendFile({ linkId: t.id, file, timestamp });
  return file;
}

it("a 115 KB voice-note-sized file goes whole over a native channel's 120 KiB send budget (it froze the Desktop app)", async () => {
  const t = await setup();
  const sent = await put(t, "voice-0001", 115_395);
  await vi.waitFor(() => expect(t.node().getState().transfers[sent.id]).toMatchObject({ state: "done", direction: "out", transferred: 115_395 }), { timeout: 20_000 });
  await vi.waitFor(() => expect(t.records.get("in:voice-0001")?.state).toBe("done"));
  // And the other way, a few MiB: the contact's frames wait for room too.
  t.offer("back-00001", 3 * 1024 * 1024 + 11);
  await vi.waitFor(async () => expect((await t.incoming("back-00001"))?.transfer).toMatchObject({ state: "done" }), { timeout: 30_000 });
  expect(await (await fileBytes()).digest((await t.incoming("back-00001"))!.fileId)).toBe(digestOf(3 * 1024 * 1024 + 11));
}, 60_000);

it("stuck after a restart, a sent file offers Send again; it goes on from the contact's bytes, one message on each side", async () => {
  const t = await setup();
  // The contact stops taking data (a session that stopped carrying it).
  let deaf = false;
  const handle = t.files.handle.bind(t.files);
  t.files.handle = async (frame) => { if (deaf && frame.t === "pf-data") return; return handle(frame); };
  const size = 3 * 1024 * 1024 + 3;
  const sent = await put(t, "stuck-0001", size, 7);
  await vi.waitFor(() => expect(t.node().getState().transfers[sent.id]?.transferred).toBeGreaterThan(1024 * 1024), { timeout: 20_000 });
  deaf = true;
  await t.restartApp();
  // Unfinished when the app started, and not moved since: stuck.
  await vi.waitFor(() => expect(t.node().getState().transfers[sent.id]).toMatchObject({ state: "transferring", direction: "out", stalled: true }));
  deaf = false;
  const accepts: number[] = [];
  const send = t.contact.sendFilesFrame.bind(t.contact);
  t.contact.sendFilesFrame = (frame) => { if (frame.t === "pf-accept") accepts.push(frame.offset as number); return send(frame); };
  t.node().fileAction({ linkId: t.id, fileId: sent.id, action: "resend" });
  await vi.waitFor(() => expect(t.node().getState().transfers[sent.id]).toMatchObject({ state: "done", transferred: size }), { timeout: 20_000 });
  expect(t.node().getState().transfers[sent.id].stalled).toBeUndefined();
  expect(accepts[0], "it went on from what the contact held").toBeGreaterThan(1024 * 1024);
  expect((await db.getMessages(t.id)).filter((m) => m.file?.id === sent.id)).toHaveLength(1);
  expect(t.records.get("in:stuck-0001")?.state).toBe("done");
  expect(() => t.node().fileAction({ linkId: t.id, fileId: sent.id, action: "request" }), "a sent file is not asked for").toThrow();
}, 90_000);

it("a received file that stopped arriving is asked for again, from where it stands here", async () => {
  const t = await setup();
  let lose = false;
  const send = t.contact.sendFilesFrame.bind(t.contact);
  t.contact.sendFilesFrame = (frame) => (lose && frame.t === "pf-data" ? true : send(frame));
  const size = 4 * 1024 * 1024 + 1;
  t.offer("ask-000001", size);
  await vi.waitFor(async () => expect((await t.incoming("ask-000001"))?.transfer?.transferred ?? 0).toBeGreaterThan(1024 * 1024), { timeout: 20_000 });
  lose = true;
  const { fileId } = (await t.incoming("ask-000001"))!;
  let last = -1;
  await vi.waitFor(() => { const now = t.node().getState().transfers[fileId].transferred; const still = now === last; last = now; expect(still).toBe(true); }, { timeout: 10_000, interval: 300 });
  lose = false;
  t.node().fileAction({ linkId: t.id, fileId, action: "request" });
  await vi.waitFor(async () => expect((await t.incoming("ask-000001"))?.transfer).toMatchObject({ state: "done", transferred: size }), { timeout: 20_000 });
  expect(await (await fileBytes()).digest(fileId)).toBe(digestOf(size));
  expect((await db.getMessages(t.id)).filter((m) => m.id === "peer_ask-000001")).toHaveLength(1);
}, 60_000);

it("sends a file to a contact with files/3, and cancels one on both sides", async () => {
  const t = await setup();
  const put1 = (wireId: string, size: number) => put(t, wireId, size);
  const sent = await put1("send-0001", 3 * 1024 * 1024 + 7);
  await vi.waitFor(() => expect(t.node().getState().transfers[sent.id]).toMatchObject({ state: "done", direction: "out" }), { timeout: 30_000 })
    .catch((e) => { throw new Error(`${e} ${JSON.stringify(t.node().getState().transfers[sent.id])} ${JSON.stringify(t.records.get("in:send-0001"))}`); });
  await vi.waitFor(() => expect(t.records.get("in:send-0001")?.state).toBe("done"));

  t.decide = () => "ask";
  const cancelled = await put1("send-0002", 1000);
  await vi.waitFor(() => expect(t.node().getState().transfers[cancelled.id]).toMatchObject({ stage: "asking" }));
  t.node().fileAction({ linkId: t.id, fileId: cancelled.id, action: "cancel" });
  await vi.waitFor(() => expect(t.records.get("in:send-0002")).toMatchObject({ state: "cancelled", error: "Cancelled by the sender" }));
}, 60_000);

const notFound = () => Object.assign(new Error("The object can not be found here."), { name: "NotFoundError" });

it("a stored file that reads in slices but not as a stream (WebKit, IndexedDB) still checks out", async () => {
  const t = await setup();
  const stream = vi.spyOn(Blob.prototype, "stream").mockImplementation(() => { throw notFound(); });
  try {
    const sent = await put(t, "slices-001", 63_899, 11);
    await vi.waitFor(() => expect(t.node().getState().transfers[sent.id]).toMatchObject({ state: "done", transferred: 63_899 }), { timeout: 20_000 });
    expect(t.records.get("in:slices-001")?.state).toBe("done");
  } finally { stream.mockRestore(); }
}, 60_000);

it("Retry never says 'already active': a failed read goes again, an unfinished transfer is taken over after a restart, a cancelled one says why", async () => {
  const t = await setup();
  const retry = (file: { id: string; name: string; size: number; mime: string }, timestamp: number) => t.node().sendFile({ linkId: t.id, file, timestamp });

  // 1. The bytes could not be read: failed, and the contact's copy stopped. Retry sends it again, whole, one message.
  const read = vi.spyOn(Blob.prototype, "arrayBuffer").mockRejectedValue(notFound());
  const unread = await put(t, "unread-001", 63_899, 12);
  await vi.waitFor(() => expect(t.node().getState().transfers[unread.id]).toMatchObject({ state: "failed", retry: true }), { timeout: 20_000 });
  expect(t.node().getState().transfers[unread.id].error).toBe("Could not read the file: The object can not be found here.");
  await vi.waitFor(() => expect(t.records.get("in:unread-001")?.state).toBe("cancelled"));
  read.mockRestore();
  retry(unread, 12);
  await vi.waitFor(() => expect(t.node().getState().transfers[unread.id]).toMatchObject({ state: "done", transferred: 63_899 }), { timeout: 20_000 });
  expect(t.records.get("in:unread-001")?.state).toBe("done");
  expect((await db.getMessages(t.id)).filter((m) => m.file?.id === unread.id)).toHaveLength(1);

  // 2. Unfinished when the app restarts (the contact takes nothing meanwhile): Retry takes the transfer over.
  let deaf = false;
  const handle = t.files.handle.bind(t.files);
  t.files.handle = async (frame) => { if (deaf && frame.t === "pf-data") return; return handle(frame); };
  const size = 2 * 1024 * 1024 + 1;
  const stuck = await put(t, "restart-01", size, 13);
  await vi.waitFor(() => expect(t.node().getState().transfers[stuck.id]?.transferred).toBeGreaterThan(0), { timeout: 20_000 });
  deaf = true;
  await t.restartApp();
  deaf = false;
  retry(stuck, 13);
  await vi.waitFor(() => expect(t.node().getState().transfers[stuck.id]).toMatchObject({ state: "done", transferred: size }), { timeout: 20_000 });
  expect(JSON.stringify(t.node().getState().transfers)).not.toContain("already active");

  // 3. Cancelled by the contact: Retry leaves the reason, not "already active", and offers no Retry.
  t.decide = () => "ask";
  const refused = await put(t, "refused-01", 1000, 14);
  await vi.waitFor(() => expect(t.node().getState().transfers[refused.id]).toMatchObject({ stage: "asking" }));
  t.files.cancel("in", "refused-01");
  await vi.waitFor(() => expect(t.node().getState().transfers[refused.id]).toMatchObject({ state: "failed", error: "Cancelled by your contact" }));
  retry(refused, 14);
  await new Promise((resolve) => setTimeout(resolve, 300));
  expect(t.node().getState().transfers[refused.id]).toMatchObject({ state: "failed", error: "Cancelled by your contact", direction: "out" });
  expect(t.node().getState().transfers[refused.id].retry).toBeFalsy();
}, 120_000);

it("a file sent while the chat is not live waits, and goes whole once it is, after a restart too (WebKit's Blob stream failing)", async () => {
  const t = await setup();
  // As WebKit did with IndexedDB Blobs: slices read, a stream does not. It must not matter.
  const stream = vi.spyOn(Blob.prototype, "stream").mockImplementation(() => { throw notFound(); });
  try {
    t.contact.disconnect();
    await vi.waitFor(() => expect(t.files.live).toBe(false));
    const waiting = await put(t, "queued-001", 76_232, 21);
    await vi.waitFor(async () => expect((await db.getMessages(t.id)).find((m) => m.file?.id === waiting.id)?.delivery).toBe("waiting"));
    void t.contact.connect(5_000).catch(() => {});
    await vi.waitFor(() => expect(t.node().getState().transfers[waiting.id]).toMatchObject({ state: "done", transferred: 76_232 }), { timeout: 30_000 });
    expect(t.records.get("in:queued-001")?.state).toBe("done");

    // Queued, then the app restarts before the chat is live again.
    t.contact.disconnect();
    await vi.waitFor(() => expect(t.files.live).toBe(false));
    const later = await put(t, "queued-002", 20_986, 22);
    await vi.waitFor(async () => expect((await db.getMessages(t.id)).find((m) => m.file?.id === later.id)?.delivery).toBe("waiting"));
    await t.restartApp();
    await vi.waitFor(() => expect(t.node().getState().transfers[later.id]).toMatchObject({ state: "done", transferred: 20_986 }), { timeout: 30_000 });
    expect(t.records.get("in:queued-002")?.state).toBe("done");
    expect((await db.getMessages(t.id)).filter((m) => m.file?.id === later.id)).toHaveLength(1);
  } finally { stream.mockRestore(); }
}, 120_000);
