import {readFile,writeFile} from 'node:fs/promises';
import solc from 'solc';
import {ContractFactory,JsonRpcProvider} from 'ethers';
if(process.env.GHOSTLY_USDT_LOCAL!=='1')throw new Error('Explicit local test opt-in required');
const provider=new JsonRpcProvider('http://127.0.0.1:43210');
if((await provider.getNetwork()).chainId!==31337n)throw new Error('Local chain31337 required');
const input={language:'Solidity',sources:{'TestUSDT.sol':{content:await readFile(new URL('../contracts/TestUSDT.sol',import.meta.url),'utf8')}},settings:{evmVersion:'paris',outputSelection:{'*':{'*':['abi','evm.bytecode']}}}};
const compiled=JSON.parse(solc.compile(JSON.stringify(input)));
if(compiled.errors?.some(e=>e.severity==='error'))throw new Error('Test contract compilation failed');
const artifact=compiled.contracts['TestUSDT.sol'].TestUSDT;
const contract=await new ContractFactory(artifact.abi,artifact.evm.bytecode.object,await provider.getSigner(0)).deploy(6);
await contract.waitForDeployment();
const config={network:'evm-local',chainId:31337,provider:'http://127.0.0.1:43210',token:await contract.getAddress(),decimals:6};
await writeFile('/tmp/ghostly-usdt-local.json',JSON.stringify(config));
console.log(JSON.stringify({token:config.token,chainId:31337,label:'TEST-USDT — local fixture, not issued by Tether',compiler:solc.version()}));
provider.destroy();
