// /llms.txt and /llms-full.txt (the llms.txt convention, llmstxt.org): what an AI reader should know about Ghostly,
// generated by sync-references.mjs from the same sources as the site (docs/wisps and the reference index), so the
// two files never drift from the pages. Nothing here is text per WISP: a WISP's line is its header's Summary row.
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

export const SITE = "https://ghostly.tools";
const REPO = "https://github.com/MiguelMedeiros/ghostly";
const RAW = "https://raw.githubusercontent.com/MiguelMedeiros/ghostly/dev";

/** Documents of the repository that llms-full.txt carries after the WISPs, besides the published references. */
export const KEY_DOCS = ["docs/CLI.md", "docs/AI-AGENTS.md", "packages/cli/SKILL.md"];

/** Published references (not WISPs) that llms-full.txt carries, and the index lists under "How it works". */
const HOW = [
  ["PROTOCOL.md", "the protocol in long form: records, keys and how two apps meet"],
  ["DHT-DELIVERY.md", "how short texts travel over the DHT when no live link connects"],
  ["MAP.md", "how the Ghost core composes with transports, capabilities and local state"],
];

const reader = (slug) => `${SITE}/developers/wisps/${slug}`;
const number = (entry) => Number(entry.id);

/** The WISPs, in number order, each with its reference entry (title, slug, the header's Summary as `benefit`). */
export function wispsOf(entries, numbering) {
  return [...numbering]
    .sort((a, b) => number(a) - number(b))
    .map((wisp) => {
      const entry = entries.find((e) => e.file === wisp.file);
      if (!entry) throw new Error(`llms.txt: no reference entry for ${wisp.file}`);
      return entry;
    });
}

const line = (title, url, note) => `- [${title}](${url})${note ? `: ${note}` : ""}`;

/** llms.txt: an H1, a one-paragraph summary, then sections of links with one line each. */
export function llmsIndex(entries, numbering) {
  const wisps = wispsOf(entries, numbering);
  const listed = new Set([...wisps.map((e) => e.file), ...HOW.map(([file]) => file), "SDK.md"]);
  const bySlug = (file) => entries.find((e) => e.file === file);
  const other = entries.filter((e) => !listed.has(e.file));
  return `# Ghostly

> An end-to-end encrypted, peer-to-peer messenger with a wallet and verifiable identities built in. No Ghostly server, no account. Two apps meet through small signed records on the Mainline DHT, then talk over a direct link. Every wire contract is an open draft called a WISP, and a headless CLI lets bots and AI agents join the same chats as people.

Every WISP has the document status Draft; each says what is implemented. A page under ${SITE}/developers/wisps/ has its Markdown source at ${SITE}/reference/<file>.md. The WISPs, the CLI guide and the agent skill are in one file: ${SITE}/llms-full.txt.

## Ghostly

${[
  line("Ghostly", `${SITE}/`, "what the app does: chats, wallets, identity proofs, files, calls and groups"),
  line("Web app", "https://app.ghostly.tools", "Ghostly in the browser, nothing to install"),
  line("Download", `${REPO}/releases/latest`, "macOS, Windows, Linux and the browser extension"),
  line("Roadmap", `${SITE}/roadmap`, "what comes next, in dependency order, with no dates"),
].join("\n")}

## How it works

${[
  line("How a chat starts", `${SITE}/developers`, "two apps publish signed records, find each other, agree on what both speak and open a direct link, step by step"),
  ...HOW.map(([file, note]) => line(bySlug(file).title, reader(bySlug(file).slug), note)),
  line("Compatibility record guide", `${SITE}/docs`, "record formats of chats with Ghostly 0.4 contacts (WISP 402)"),
].join("\n")}

## Developers

${[
  line("Developers", `${SITE}/developers`, "the introduction: how a chat starts, how transports are ranked, and where each feature runs"),
  line("WISP catalog", `${SITE}/developers/wisps`, "every WISP with its status and implementations"),
  line(bySlug("SDK.md").title, reader(bySlug("SDK.md").slug)),
  line("Source code", REPO, "MIT licensed"),
].join("\n")}

## WISPs

${wisps.map((e) => line(e.title, reader(e.slug), e.benefit)).join("\n")}

## CLI

${[
  line("Ghostly CLI", `${SITE}/cli`, "ghostly, the app's engine without a screen: invites, chats, groups, files, payments and voice calls, every event a JSON line"),
  line("CLI guide", `${RAW}/docs/CLI.md`, "install, the daemon, events, the allowlist and agent turns"),
  line("Every command and event", `${RAW}/packages/cli/README.md`),
].join("\n")}

## AI agents

${[
  line("AI agents", `${SITE}/developers/agents`, "how an AI agent joins Ghostly through the CLI, what works now and what is planned"),
  line("Agent skill", `${RAW}/packages/cli/SKILL.md`, "a SKILL.md that takes an agent from install to answering in chats and groups"),
  line("Agents guide", `${RAW}/docs/AI-AGENTS.md`, "the agent connector: allowlist, agent.turn events and adapters"),
  line("Claude Code example", `${REPO}/blob/dev/packages/cli/examples/claude-code-agent.sh`, "wakes claude -p once per turn and sends its answer as a reply"),
].join("\n")}

## Optional

${[
  line("llms-full.txt", `${SITE}/llms-full.txt`, "every WISP, the protocol, the CLI guide and the agent skill in one file"),
  ...other.map((e) => line(e.title, reader(e.slug))),
].join("\n")}
`;
}

/**
 * llms-full.txt: the WISPs as published (with their revision rows), then the key documents, each under a line that
 * names its source. `read(path)` reads a file relative to the repository root.
 */
export function llmsFull(entries, numbering, read) {
  const part = (url, body) => `<!-- Source: ${url} -->\n\n${body.trim()}\n`;
  const parts = [
    ...wispsOf(entries, numbering).map((e) => part(`${SITE}/reference/${e.file}`, read(`website/public/reference/${e.file}`))),
    ...HOW.map(([file]) => part(`${SITE}/reference/${file}`, read(`website/public/reference/${file}`))),
    ...KEY_DOCS.map((path) => part(`${REPO}/blob/dev/${path}`, read(path))),
  ];
  return `# Ghostly: the full text

> Every WISP of Ghostly, the protocol and the headless CLI's guide and agent skill, in one file. The index is ${SITE}/llms.txt.

${parts.join("\n---\n\n")}`;
}

/** Writes both files to website/public, after the references are published there. */
export function writeLlms(root, entries, numbering) {
  const read = (path) => readFileSync(resolve(root, path), "utf8");
  writeFileSync(resolve(root, "website/public/llms.txt"), llmsIndex(entries, numbering));
  writeFileSync(resolve(root, "website/public/llms-full.txt"), llmsFull(entries, numbering, read));
}
