#!/usr/bin/env node
// Line coverage of the unit tests, per package (V8, through @vitest/coverage-v8).
//
//   npm run coverage                  every package that has unit tests
//   npm run coverage -- core browser  only these
//
// Each package's report lands in coverage/<name>/ (HTML in index.html), the totals in
// coverage/summary.json, and the table in the generated coverage part of docs/TESTING.md.
// Gated suites (regtest, testnet) skip themselves as usual, so what they reach is not counted.
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(fileURLToPath(import.meta.url), "..", "..");
const DOC = "docs/TESTING.md";
const START = "<!-- coverage:start (generated by `npm run coverage`; do not edit by hand) -->";
const END = "<!-- coverage:end -->";

// A place with unit tests: where vitest runs, and which sources count. Add a row when a new place
// gets tests (the extension, say); a row whose directory has no test file is skipped.
const TARGETS = [
  { name: "core", dir: "packages/core", include: ["src/**/*.{ts,tsx}"] },
  { name: "browser", dir: "packages/browser", include: ["src/**/*.{ts,tsx}"] },
  { name: "sdk", dir: "packages/sdk", include: ["src/**/*.{ts,tsx}"] },
  // The UI (src/) and @ghostly/react share one config: vitest.ui.config.ts.
  { name: "ui", dir: ".", include: ["src/**/*.{ts,tsx}", "packages/react/src/**/*.{ts,tsx}"], exclude: ["src/test/**"], config: "vitest.ui.config.ts" },
  { name: "extension", dir: "extension", include: ["src/**/*.{ts,tsx}"] },
];

const hasTests = (dir) => {
  const walk = (d) => readdirSync(d, { withFileTypes: true }).some((e) =>
    e.isDirectory() ? !["node_modules", "dist", "coverage", "packages", "e2e", "website", "examples", "target", ".claude"].includes(e.name) && walk(join(d, e.name)) : /\.test\.[cm]?[jt]sx?$/.test(e.name));
  return existsSync(dir) && walk(dir);
};

const only = process.argv.slice(2);
const results = [];
let failed = false;
for (const t of TARGETS) {
  if (only.length && !only.includes(t.name)) continue;
  const dir = join(ROOT, t.dir);
  if (t.config && !existsSync(join(dir, t.config))) continue;
  if (!hasTests(dir)) continue;
  const out = join(ROOT, "coverage", t.name);
  console.log(`\n── ${t.name} (${t.dir})`);
  const run = spawnSync("npx", [
    // Instrumented code runs slower: timing is not what this run measures.
    "vitest", "run", "--testTimeout=60000", ...(t.config ? ["-c", t.config] : []),
    "--coverage.enabled", "--coverage.provider=v8", "--coverage.reportOnFailure",
    "--coverage.reporter=json-summary", "--coverage.reporter=text-summary", "--coverage.reporter=html",
    `--coverage.reportsDirectory=${out}`,
    ...t.include.map((g) => `--coverage.include=${g}`),
    ...(t.exclude ?? []).map((g) => `--coverage.exclude=${g}`),
  ], { cwd: dir, stdio: "inherit" });
  const report = join(out, "coverage-summary.json");
  if (run.status !== 0) { failed = true; console.error(`${t.name}: some tests failed; its figures are marked`); }
  if (!existsSync(report)) continue;
  const total = JSON.parse(readFileSync(report, "utf8")).total;
  // A package made only of re-exports (the SDK) has no statements of its own: its code is counted where it lives.
  results.push({ name: t.name, dir: t.dir, failed: run.status !== 0, ...Object.fromEntries(["lines", "statements", "functions", "branches"].map((k) => [k, total[k].total ? total[k].pct : null])) });
}

if (results.length) {
  mkdirSync(join(ROOT, "coverage"), { recursive: true });
  const date = new Date().toISOString().slice(0, 10);
  writeFileSync(join(ROOT, "coverage/summary.json"), JSON.stringify({ date, packages: results }, null, 2) + "\n");
  console.log(`\n${"package".padEnd(10)} ${["lines", "stmts", "funcs", "branch"].map((h) => h.padStart(7)).join("")}`);
  const pct = (v) => (v === null ? "n/a" : `${v}%`);
  for (const r of results) console.log(`${r.name.padEnd(10)} ${[r.lines, r.statements, r.functions, r.branches].map((v) => pct(v).padStart(7)).join("")}`);

  if (!only.length) {
    const doc = readFileSync(join(ROOT, DOC), "utf8");
    const a = doc.indexOf(START), b = doc.indexOf(END);
    if (a >= 0 && b >= 0) {
      const table = [START, "", `Unit tests only, measured on ${date} with \`npm run coverage\` (gated suites skipped).`, "",
        "| Package | Lines | Statements | Functions | Branches |", "|---|---:|---:|---:|---:|",
        ...results.map((r) => `| ${r.name} (\`${r.dir}\`)${r.failed ? " — some tests failed" : ""} | ${pct(r.lines)} | ${pct(r.statements)} | ${pct(r.functions)} | ${pct(r.branches)} |`),
        ...(results.some((r) => r.lines === null) ? ["", "n/a: the package only re-exports code that lives (and is counted) elsewhere."] : []), "", END].join("\n");
      writeFileSync(join(ROOT, DOC), doc.slice(0, a) + table + doc.slice(b + END.length));
      console.log(`wrote ${DOC}`);
    }
  }
}
process.exit(failed ? 1 : 0);
