// The WISP index on GitHub: the table in docs/wisps/README.md, one row per WISP, read from each WISP's header
// table and from numbering.json, so it never says something the WISP does not. `npm run sync:references` writes
// it between the markers below; `npm test` fails when the committed table is not the one the WISPs give.
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { headerRows } from "./wisp-header.mjs";

export const START = "<!-- wisp-index:start (generated by `npm run sync:references` in apps/website/ from each WISP's header; edit the WISPs, not this table) -->";
export const END = "<!-- wisp-index:end -->";

/** Each family is a range of numbers (docs/wisps/NUMBERING.md, "Independent families"). */
const FAMILIES = [
  [0, "Foundations"],
  [100, "Transports"],
  [200, "Payments"],
  [300, "Identity"],
  [400, "Chat"],
  [500, "Files"],
  [600, "Voice and video"],
  [700, "Local services"],
  [800, "Invites"],
  [900, "Groups"],
  [1000, "Storage"],
  [1100, "Headless"],
  [1200, "Apps and plugins"],
];

export function familyOf(id) {
  const n = Number(id);
  return FAMILIES.filter(([from]) => n >= from).at(-1)[1];
}

const cell = (text) => text.replace(/\|/g, "\\|").trim();

/** The index table, in number order, from numbering.json and a reader of each WISP's Markdown. */
export function wispIndex(numbering, read) {
  const rows = [...numbering]
    .sort((a, b) => Number(a.id) - Number(b.id))
    .map((entry) => {
      const body = read(entry.file);
      const header = Object.fromEntries(headerRows(body));
      const title = (body.match(/^#\s+(.+)$/m)?.[1] ?? entry.file).replace(/^WISP\s+\S+:\s*/, "");
      const status = header.Status;
      const availability = header.Availability;
      if (!status) throw new Error(`docs/wisps/${entry.file}: no "Status" row in its header`);
      if (!availability) throw new Error(`docs/wisps/${entry.file}: no "Availability" row in its header`);
      return `| ${entry.displayNumber} | ${familyOf(entry.id)} | [${cell(title)}](${entry.file}) | ${entry.kind} | ${cell(status)} | ${cell(availability)} |`;
    });
  return ["| Number | Family | Title | Type | Status | Availability |", "|---|---|---|---|---|---|", ...rows].join("\n");
}

/** The README with its index block replaced by `table`. */
export function withIndex(readme, table) {
  const start = readme.indexOf(START);
  const end = readme.indexOf(END);
  if (start < 0 || end < start) throw new Error(`docs/wisps/README.md: the index markers are missing (${START} … ${END})`);
  return `${readme.slice(0, start)}${START}\n\n${table}\n\n${readme.slice(end)}`;
}

/** Where the index lives, from the repository root. */
export const README = "docs/wisps/README.md";

/** The README as it should be, from the WISPs of the repository at `root`. */
export function expectedReadme(root) {
  const numbering = JSON.parse(readFileSync(resolve(root, "docs/wisps/numbering.json"), "utf8"));
  const readme = readFileSync(resolve(root, README), "utf8");
  return withIndex(readme, wispIndex(numbering, (file) => readFileSync(resolve(root, "docs/wisps", file), "utf8")));
}
